# import './fragments.graphql'

fragment TokenData on Token {
  id
  address
  name
  symbol
  decimals
  isMock
}

fragment RoleProviderData on RoleProvider {
  id
  providerAddress
  timeToLive
  isPullProvider
  pullProviderIndex
  isPushProvider
  pushProviderIndex
  isApproved
}

fragment LenderHooksAccessData on LenderHooksAccess {
  id
  lender
  isBlockedFromDeposits
  lastProvider {
    ...RoleProviderData
  }
  canRefresh
  lastApprovalTimestamp
}

# ========================================================================== #
#                                Lender Views                                #
# ========================================================================== #

fragment AccountDataForLenderView on LenderAccount {
  ...LenderProperties

  controllerAuthorization {
    authorized
  }

  hooksAccess {
    ...LenderHooksAccessData
  }

  knownLenderStatus {
    id
  }

  deposits(
    first: $numDeposits
    skip: $skipDeposits
    orderBy: $orderDeposits
    orderDirection: $directionDeposits
  ) {
    ...DepositData
  }
}

# Lender data with:
# address
# information needed to derive current balance with interest
# time added
# access level & authorization source (if any)
fragment BasicLenderData on LenderAccount {
  id
  address

  scaledBalance

  role
  controllerAuthorization {
    authorized
  }
  hooksAccess {
    ...LenderHooksAccessData
  }
  knownLenderStatus {
    id
  }
}

fragment LenderProperties on LenderAccount {
  id
  address
  scaledBalance
  role
  totalDeposited
  lastScaleFactor
  lastUpdatedTimestamp
  totalInterestEarned
  numPendingWithdrawalBatches
}

fragment AllAuthorizedLendersView on LenderAuthorization {
  lender
  authorized
  changes(first: 1, orderBy: blockTimestamp, orderDirection: desc) {
    blockTimestamp
  }
}

# ============================================================================ #
#                                Borrower Views                                #
# ============================================================================ #

fragment MarketData on Market {
  id
  version

  # ================================= Config ================================= #
  isRegistered
  isClosed
  controller {
    id
  }
  borrower
  sentinel
  feeRecipient
  name
  symbol
  decimals
  protocolFeeBips
  delinquencyGracePeriod
  delinquencyFeeBips
  withdrawalBatchDuration

  _asset: asset {
    ...TokenData
  }

  hooksConfig {
    ...HooksConfigDataForMarket
  }
  hooks {
    ...HooksInstanceData
  }

  # ================================== State ================================= #
  maxTotalSupply
  pendingProtocolFees
  normalizedUnclaimedWithdrawals
  scaledTotalSupply
  scaledPendingWithdrawals
  pendingWithdrawalExpiry
  isDelinquent
  timeDelinquent
  annualInterestBips
  reserveRatioBips
  scaleFactor
  lastInterestAccruedTimestamp
  originalAnnualInterestBips
  originalReserveRatioBips
  temporaryReserveRatioExpiry
  temporaryReserveRatioActive

  # ================================ Metadata ================================ #
  totalBorrowed
  totalRepaid
  totalBaseInterestAccrued
  totalDelinquencyFeesAccrued
  totalProtocolFeesAccrued
  totalDeposited
  eventIndex

  deployedEvent {
    ...MarketDeployedEvent
  }
}

fragment AprConstraints on ParameterConstraints {
  minimumAnnualInterestBips
  maximumAnnualInterestBips
}

# ============================================================================ #
#                                    Events                                    #
# ============================================================================ #

fragment DelinquencyStatusChangedData on DelinquencyStatusChanged {
  id
  eventIndex
  isDelinquent
  liquidityCoverageRequired
  totalAssets
  blockNumber
  blockTimestamp
  transactionHash
}

fragment DepositData on Deposit {
  id
  eventIndex
  account {
    address
  }
  assetAmount
  scaledAmount
  blockNumber
  blockTimestamp
  transactionHash
}

fragment MarketDeployedEvent on MarketDeployed {
  blockNumber
  blockTimestamp
  transactionHash
}

fragment MarketDataWithEvents on Market {
  ...MarketData
  ...MarketRecords @skip(if: $shouldSkipRecords)
}

fragment WithdrawalBatchPaymentProperties on WithdrawalBatchPayment {
  id
  scaledAmountBurned
  normalizedAmountPaid
  blockNumber
  blockTimestamp
  transactionHash
}
fragment WithdrawalRequestProperties on WithdrawalRequest {
  id
  eventIndex
  requestIndex
  account {
    address
  }
  scaledAmount
  normalizedAmount
  blockNumber
  blockTimestamp
  transactionHash
}
fragment WithdrawalExecutionProperties on WithdrawalExecution {
  id
  account {
    address
  }
  normalizedAmount
  blockNumber
  blockTimestamp
  transactionHash
}

fragment LenderWithdrawalProperties on LenderWithdrawalStatus {
  id
  account {
    address
  }
  requestsCount
  executionsCount
  scaledAmount
  normalizedAmountWithdrawn
  totalNormalizedRequests
  isCompleted
}

fragment ForceBuyBackData on ForceBuyBack {
  id
  account {
    address
  }
  eventIndex
  withdrawalExpiry
  scaledAmount
  normalizedAmount
  blockNumber
  blockTimestamp
  transactionHash
}

fragment MinimumDepositUpdatedData on MinimumDepositUpdated {
  id
  eventIndex
  oldMinimumDeposit
  newMinimumDeposit
  blockNumber
  blockTimestamp
  transactionHash
}

fragment ProtocolFeeBipsUpdatedData on ProtocolFeeBipsUpdated {
  id
  protocolFeeBipsUpdatedIndex
  eventIndex
  oldProtocolFeeBips
  newProtocolFeeBips
  blockNumber
  blockTimestamp
  transactionHash
}

fragment DisabledForceBuyBacksData on DisabledForceBuyBacks {
  id
  blockNumber
  blockTimestamp
  transactionHash
  eventIndex
}

fragment FixedTermUpdatedData on FixedTermUpdated {
  id
  oldFixedTermEndTime
  newFixedTermEndTime
  blockNumber
  blockTimestamp
  transactionHash
  eventIndex
  fixedTermUpdatedIndex
}

fragment LenderWithdrawalPropertiesWithEvents on LenderWithdrawalStatus {
  ...LenderWithdrawalProperties

  batch {
    ...WithdrawalBatchProperties
  }
  requests {
    ...WithdrawalRequestProperties
  }
  executions {
    ...WithdrawalExecutionProperties
  }
}

fragment WithdrawalBatchProperties on WithdrawalBatch {
  id
  expiry
  scaledTotalAmount
  scaledAmountBurned
  normalizedAmountPaid
  normalizedAmountClaimed
  totalNormalizedRequests
  isExpired
  isClosed
  isCompleted
  paymentsCount
  lastScaleFactor
  lastUpdatedTimestamp
  totalInterestEarned

  creation {
    blockNumber
    blockTimestamp
    transactionHash
  }

  payments {
    ...WithdrawalBatchPaymentProperties
  }
}

fragment WithdrawalBatchPropertiesWithEvents on WithdrawalBatch {
  ...WithdrawalBatchProperties

  withdrawals {
    ...LenderWithdrawalProperties
  }
  requests {
    ...WithdrawalRequestProperties
  }
  executions {
    ...WithdrawalExecutionProperties
  }
}

fragment MarketRecords on Market {
  depositRecords(
    first: $numDeposits
    skip: $skipDeposits
    orderBy: $orderDeposits
    orderDirection: $directionDeposits
  ) {
    ...DepositData
  }
  borrowRecords(
    first: $numBorrows
    skip: $skipBorrows
    orderBy: $orderBorrows
    orderDirection: $directionBorrows
  ) {
    ...BorrowData
  }
  feeCollectionRecords(
    first: $numFeeCollections
    skip: $skipFeeCollections
    orderBy: $orderFeeCollections
    orderDirection: $directionFeeCollections
  ) {
    ...FeesCollectedData
  }
  repaymentRecords(
    first: $numRepayments
    skip: $skipRepayments
    orderBy: $orderRepayments
    orderDirection: $directionRepayments
  ) {
    ...RepaymentData
  }
}

fragment BorrowData on Borrow {
  eventIndex
  assetAmount
  blockNumber
  blockTimestamp
  transactionHash
}

fragment RepaymentData on DebtRepaid {
  eventIndex
  from
  assetAmount
  blockNumber
  blockTimestamp
  transactionHash
}

fragment FeesCollectedData on FeesCollected {
  eventIndex
  feesCollected
  blockNumber
  blockTimestamp
  transactionHash
}

fragment AnnualInterestBipsUpdatedData on AnnualInterestBipsUpdated {
  eventIndex
  oldAnnualInterestBips
  newAnnualInterestBips
  blockNumber
  blockTimestamp
  transactionHash
}

fragment MaxTotalSupplyUpdatedData on MaxTotalSupplyUpdated {
  eventIndex
  oldMaxTotalSupply
  newMaxTotalSupply
  blockNumber
  blockTimestamp
  transactionHash
}

fragment MarketClosedData on MarketClosed {
  eventIndex
  blockNumber
  blockTimestamp
  transactionHash
}

# ========================================================================== #
#                                 V2 Markets                                 #
# ========================================================================== #

fragment HooksConfigDataForMarket on HooksConfig {
  id
  # Exclude hooks, market
  useOnDeposit
  useOnQueueWithdrawal
  useOnExecuteWithdrawal
  useOnTransfer
  useOnBorrow
  useOnRepay
  useOnCloseMarket
  useOnNukeFromOrbit
  useOnSetMaxTotalSupply
  useOnSetAnnualInterestAndReserveRatioBips
  useOnSetProtocolFeeBips

  # Common config values
  depositRequiresAccess
  transferRequiresAccess
  transfersDisabled
  minimumDeposit
  allowForceBuyBacks

  # FixedTermHooks config values
  queueWithdrawalRequiresAccess
  fixedTermEndTime
  allowClosureBeforeTerm
  allowTermReduction
}

fragment HooksInstanceData on HooksInstance {
  id
  borrower
  name
  kind
  hooksTemplate {
    ...HooksTemplateData
  }
  providers {
    ...RoleProviderData
  }
  eventIndex
}

fragment HooksTemplateData on HooksTemplate {
  id
  name
  feeRecipient
  protocolFeeBips
  originationFeeAsset {
    ...TokenData
  }
  originationFeeAmount
  disabled
}
