# import './fragments.graphql'

# -------------------------------------------------------------------------- #
#                                Lender Views                                #
# -------------------------------------------------------------------------- #

query getLenderAccountForMarket(
  $market: ID!
  $lender: Bytes!
  $numDeposits: Int = 200
  $skipDeposits: Int = 0
  $orderDeposits: Deposit_orderBy = blockTimestamp
  $directionDeposits: OrderDirection = desc
) {
  market(id: $market) {
    lenders(where: { address: $lender }) {
      ...AccountDataForLenderView
    }
  }
}

query getLenderAccountWithMarket(
  $market: ID!
  $lender: Bytes!
  $numDeposits: Int = 200
  $skipDeposits: Int = 0
  $orderDeposits: Deposit_orderBy = blockTimestamp
  $directionDeposits: OrderDirection = desc
  # borrowRecords
  $numBorrows: Int = 10
  $skipBorrows: Int = 0
  $orderBorrows: Borrow_orderBy = blockTimestamp
  $directionBorrows: OrderDirection = desc
  # repaymentRecords
  $numRepayments: Int = 10
  $skipRepayments: Int = 0
  $orderRepayments: DebtRepaid_orderBy = blockTimestamp
  $directionRepayments: OrderDirection = desc
) {
  market(id: $market) {
    lenders(where: { address: $lender }) {
      ...AccountDataForLenderView
    }
    ...MarketData
    borrowRecords(
      first: $numBorrows
      skip: $skipBorrows
      orderBy: $orderBorrows
      orderDirection: $directionBorrows
    ) {
      ...BorrowData
    }
    repaymentRecords(
      first: $numRepayments
      skip: $skipRepayments
      orderBy: $orderRepayments
      orderDirection: $directionRepayments
    ) {
      ...RepaymentData
    }
  }
}

# Check whether a borrower is registered and has any markets
query getBasicBorrowerData($borrower: Bytes!) {
  registeredBorrowers(where: { borrower: $borrower }, first: 1) {
    isRegistered
  }
  markets(where: { borrower: $borrower }, first: 1) {
    id
  }
}

# Get all markets, including lender account if lender is authorized
query getAllMarketsForLenderView(
  $lender: Bytes
  # markets - default order is newest first
  $marketFilter: Market_filter = { id_not: null }
  $numMarkets: Int = 1000
  $skipMarkets: Int = 0
  $orderMarkets: Market_orderBy = createdAt
  $directionMarkets: OrderDirection = desc
  # deposits
  $numDeposits: Int = 10
  $skipDeposits: Int = 0
  $orderDeposits: Deposit_orderBy = blockTimestamp
  $directionDeposits: OrderDirection = desc
  # borrowRecords
  $numBorrows: Int = 10
  $skipBorrows: Int = 0
  $orderBorrows: Borrow_orderBy = blockTimestamp
  $directionBorrows: OrderDirection = desc
  # repaymentRecords
  $numRepayments: Int = 10
  $skipRepayments: Int = 0
  $orderRepayments: DebtRepaid_orderBy = blockTimestamp
  $directionRepayments: OrderDirection = desc
) {
  markets(
    where: $marketFilter
    orderBy: $orderMarkets
    orderDirection: $directionMarkets
    first: $numMarkets
    skip: $skipMarkets
  ) {
    ...MarketData
    borrowRecords(
      first: $numBorrows
      skip: $skipBorrows
      orderBy: $orderBorrows
      orderDirection: $directionBorrows
    ) {
      ...BorrowData
    }
    repaymentRecords(
      first: $numRepayments
      skip: $skipRepayments
      orderBy: $orderRepayments
      orderDirection: $directionRepayments
    ) {
      ...RepaymentData
    }
    lenders(where: { address: $lender }, first: 1) {
      ...AccountDataForLenderView
    }
  }
  controllerAuthorizations: lenderAuthorizations(
    where: { and: [{ lender: $lender }, { authorized: true }] }
  ) {
    lender
    authorized
    controller {
      markets {
        id
      }
    }
  }
}

query getAllMarketsForLenderListView(
  $lender: Bytes
  # markets - default order is newest first
  $marketFilter: Market_filter = { id_not: null }
  $numMarkets: Int = 1000
  $skipMarkets: Int = 0
  $orderMarkets: Market_orderBy = createdAt
  $directionMarkets: OrderDirection = desc
) {
  markets(
    where: $marketFilter
    orderBy: $orderMarkets
    orderDirection: $directionMarkets
    first: $numMarkets
    skip: $skipMarkets
  ) {
    ...MarketListData
    lenders(where: { address: $lender }, first: 1) {
      ...AccountDataForLenderListView
    }
  }
  controllerAuthorizations: lenderAuthorizations(
    where: { and: [{ lender: $lender }, { authorized: true }] }
  ) {
    lender
    authorized
    controller {
      markets {
        id
      }
    }
  }
}

# Get only markets where lender is authorized or active, including lender account
query getAccountsWhereLenderAuthorizedOrActive(
  $lender: Bytes!
  $accountFilter: LenderAccount_filter = { address_not: null }
  # deposits
  $numDeposits: Int = 200
  $skipDeposits: Int = 0
  $orderDeposits: Deposit_orderBy = blockTimestamp
  $directionDeposits: OrderDirection = desc
  # borrowRecords
  $numBorrows: Int = 10
  $skipBorrows: Int = 0
  $orderBorrows: Borrow_orderBy = blockTimestamp
  $directionBorrows: OrderDirection = desc
  # repaymentRecords
  $numRepayments: Int = 10
  $skipRepayments: Int = 0
  $orderRepayments: DebtRepaid_orderBy = blockTimestamp
  $directionRepayments: OrderDirection = desc
) {
  lenderAccounts(
    where: {
      and: [
        $accountFilter
        { address: $lender }
        {
          or: [
            { role_in: [DepositAndWithdraw, WithdrawOnly] }
            { scaledBalance_gt: 0 }
            { controllerAuthorization_: { authorized: true } }
            { knownLenderStatus_: { id_not: null } }
            { hooksAccess_: { lastApprovalTimestamp_gt: 0 } }
            { totalDeposited_gt: 0 }
          ]
        }
      ]
    }
  ) {
    ...AccountDataForLenderView
    market {
      ...MarketData
      borrowRecords(
        first: $numBorrows
        skip: $skipBorrows
        orderBy: $orderBorrows
        orderDirection: $directionBorrows
      ) {
        ...BorrowData
      }
      repaymentRecords(
        first: $numRepayments
        skip: $skipRepayments
        orderBy: $orderRepayments
        orderDirection: $directionRepayments
      ) {
        ...RepaymentData
      }
    }
  }
  controllerAuthorizations: lenderAuthorizations(
    where: { and: [{ lender: $lender }, { authorized: true }] }
  ) {
    lender
    authorized
    controller {
      markets {
        ...MarketData
        borrowRecords(
          first: $numBorrows
          skip: $skipBorrows
          orderBy: $orderBorrows
          orderDirection: $directionBorrows
        ) {
          ...BorrowData
        }
        repaymentRecords(
          first: $numRepayments
          skip: $skipRepayments
          orderBy: $orderRepayments
          orderDirection: $directionRepayments
        ) {
          ...RepaymentData
        }
      }
    }
  }
}

query getLenderWithdrawalsForMarket(
  $market: ID!
  $lender: Bytes!
  $numWithdrawals: Int = 200
  $skipWithdrawals: Int = 0
) {
  market(id: $market) {
    lenders(where: { address: $lender }) {
      incompleteWithdrawals: withdrawals(
        first: $numWithdrawals
        skip: $skipWithdrawals
        where: { isCompleted: false }
      ) {
        ...LenderWithdrawalPropertiesWithEvents
      }

      completeWithdrawals: withdrawals(
        first: $numWithdrawals
        skip: $skipWithdrawals
        where: { isCompleted: true }
      ) {
        ...LenderWithdrawalPropertiesWithEvents
      }
    }
  }
}

query getLenderAuthorizationByMarket($market: ID!, $lender: Bytes!) {
  market(id: $market) {
    controller {
      authorizedLenders(where: { lender: $lender }) {
        lender
        authorized
      }
    }
  }
}

# Get market address and lender interaction logs for markets
# where lender is authorized on controller, has a role or has
# a balance.
query getMarketsAndLogsWhereLenderAuthorizedOrActive(
  $lender: Bytes!
  $minimumBalance: BigInt = 1
  $accountFilter: LenderAccount_filter = { address_not: null }
  $numAccounts: Int = 1000
  $skipAccounts: Int = 0
  $orderAccounts: LenderAccount_orderBy = lastUpdatedTimestamp
  $directionAccounts: OrderDirection = desc
  # deposits
  $numDeposits: Int = 200
  $skipDeposits: Int = 0
  $orderDeposits: Deposit_orderBy = blockTimestamp
  $directionDeposits: OrderDirection = desc
  # withdrawals
  $numWithdrawals: Int = 200
  $skipWithdrawals: Int = 0 # $orderWithdrawals: LenderWithdrawalStatus_orderBy = batch__expiry # $directionWithdrawals: OrderDirection = desc
) {
  lenderAccounts(
    where: {
      and: [
        {
          address: $lender
          or: [
            { role_in: [DepositAndWithdraw, WithdrawOnly] }
            { scaledBalance_gt: $minimumBalance }
            { controllerAuthorization_: { authorized: true } }
          ]
        }
        $accountFilter
      ]
    }
    first: $numAccounts
    skip: $skipAccounts
    orderBy: $orderAccounts
    orderDirection: $directionAccounts
  ) {
    market {
      id
    }
    scaledBalance
    role
    totalDeposited
    lastScaleFactor
    totalInterestEarned
    controllerAuthorization {
      authorized
    }
    withdrawals(
      first: $numWithdrawals
      skip: $skipWithdrawals
      where: { isCompleted: false } # orderBy: $orderWithdrawals # orderDirection: $directionWithdrawals
    ) {
      ...LenderWithdrawalProperties

      batch {
        ...WithdrawalBatchProperties
      }
      requests {
        ...WithdrawalRequestProperties
      }
      executions {
        ...WithdrawalExecutionProperties
      }
    }

    deposits(
      first: $numDeposits
      skip: $skipDeposits
      orderBy: $orderDeposits
      orderDirection: $directionDeposits
    ) {
      ...DepositData
    }
  }
}

query getAllHooksTemplates($borrower: Bytes, $includeBorrower: Boolean!) {
  hooksTemplateRegistrations {
    ...HooksTemplateRegistrationData
  }
  registeredBorrowers(where: { borrower: $borrower }, first: 1) @include(if: $includeBorrower) {
    isRegistered
  }
}

query getHooksInstancesForBorrower($borrower: Bytes!) {
  hooksInstances(where: { borrower: $borrower }) {
    ...HooksInstanceData
  }
}

query getAllHooksDataForBorrower($borrower: Bytes!) {
  hooksTemplateRegistrations {
    ...HooksTemplateRegistrationData
  }
  hooksInstances(where: { borrower: $borrower }) {
    ...HooksInstanceData
  }
  registeredBorrowers(where: { borrower: $borrower }, first: 1) {
    isRegistered
  }
  controllers(where: { borrower: $borrower }, first: 1) {
    ...MinimalControllerData
  }
}

query getIndexerDeployment {
  indexerDeployments(first: 1) {
    id
    chainId
    network
    graphNetwork
    schemaRelease
    configDigest
    archController
    sanctionsSentinel
    analyticsEnabled
    collateralEnabled
    wrappersEnabled
    pricingMode
    firstObservedBlock
    firstObservedTimestamp
    firstObservedTransaction
    firstObservedLogIndex
  }
}

query getHooksFactories {
  hooksFactories {
    ...HooksFactoryData
  }
}

# query

query getMarketEvents(
  $market: ID!
  $startEventIndex: Int = 0
  $endEventIndex: Int = 100000000
  $limit: Int = 10
  $delinquencyRecordsFilter: DelinquencyStatusChanged_filter = { id_not: null }
  $borrowRecordsFilter: Borrow_filter = { id_not: null }
  $depositRecordsFilter: Deposit_filter = { id_not: null }
  $feeCollectionRecordsFilter: FeesCollected_filter = { id_not: null }
  $repaymentRecordsFilter: DebtRepaid_filter = { id_not: null }
  $annualInterestBipsUpdatedRecordsFilter: AnnualInterestBipsUpdated_filter = { id_not: null }
  $maxTotalSupplyUpdatedRecordsFilter: MaxTotalSupplyUpdated_filter = { id_not: null }
  $withdrawalRequestRecordsFilter: WithdrawalRequest_filter = { id_not: null }
  $forceBuyBackRecordsFilter: ForceBuyBack_filter = { id_not: null }
  $minimumDepositUpdateRecordsFilter: MinimumDepositUpdated_filter = { id_not: null }
  $protocolFeeBipsUpdatedRecordsFilter: ProtocolFeeBipsUpdated_filter = { id_not: null }
  $fixedTermUpdatedRecordsFilter: FixedTermUpdated_filter = { id_not: null }
  $periodicTermUpdatedRecordsFilter: PeriodicTermUpdated_filter = { id_not: null }
  $annualInterestBipsReductionProposalRecordsFilter: AnnualInterestBipsReductionProposed_filter = { id_not: null }
) {
  market(id: $market) {
    marketClosedEvent {
      ...MarketClosedData
    }
    periodicTermClosedRecord {
      ...PeriodicTermClosedData
    }
    forceBuyBackDisabledRecord {
      ...DisabledForceBuyBacksData
    }
    delinquencyRecords(
      where: {
        and: [
          $delinquencyRecordsFilter
          { eventIndex_gte: $startEventIndex, eventIndex_lt: $endEventIndex }
        ]
      }
      orderBy: eventIndex
      orderDirection: desc
      first: $limit
    ) {
      ...DelinquencyStatusChangedData
    }
    borrowRecords(
      where: {
        and: [
          $borrowRecordsFilter
          { eventIndex_gte: $startEventIndex, eventIndex_lt: $endEventIndex }
        ]
      }
      orderBy: eventIndex
      orderDirection: desc
      first: $limit
    ) {
      ...BorrowData
    }
    depositRecords(
      where: {
        and: [
          $depositRecordsFilter
          { eventIndex_gte: $startEventIndex, eventIndex_lt: $endEventIndex }
        ]
      }
      orderBy: eventIndex
      orderDirection: desc
      first: $limit
    ) {
      ...DepositData
    }
    feeCollectionRecords(
      where: {
        and: [
          $feeCollectionRecordsFilter
          { eventIndex_gte: $startEventIndex, eventIndex_lt: $endEventIndex }
        ]
      }
      orderBy: eventIndex
      orderDirection: desc
      first: $limit
    ) {
      ...FeesCollectedData
    }
    repaymentRecords(
      where: {
        and: [
          $repaymentRecordsFilter
          { eventIndex_gte: $startEventIndex, eventIndex_lt: $endEventIndex }
        ]
      }
      orderBy: eventIndex
      orderDirection: desc
      first: $limit
    ) {
      ...RepaymentData
    }
    annualInterestBipsUpdatedRecords(
      where: {
        and: [
          $annualInterestBipsUpdatedRecordsFilter
          { eventIndex_gte: $startEventIndex, eventIndex_lt: $endEventIndex }
        ]
      }
      orderBy: eventIndex
      orderDirection: desc
      first: $limit
    ) {
      ...AnnualInterestBipsUpdatedData
    }
    maxTotalSupplyUpdatedRecords(
      where: {
        and: [
          $maxTotalSupplyUpdatedRecordsFilter
          { eventIndex_gte: $startEventIndex, eventIndex_lt: $endEventIndex }
        ]
      }
      orderBy: eventIndex
      orderDirection: desc
      first: $limit
    ) {
      ...MaxTotalSupplyUpdatedData
    }
    withdrawalRequestRecords(
      where: {
        and: [
          $withdrawalRequestRecordsFilter
          { eventIndex_gte: $startEventIndex, eventIndex_lt: $endEventIndex }
        ]
      }
      orderBy: eventIndex
      orderDirection: desc
      first: $limit
    ) {
      ...WithdrawalRequestProperties
    }
    forceBuyBackRecords(
      where: {
        and: [
          $forceBuyBackRecordsFilter
          { eventIndex_gte: $startEventIndex, eventIndex_lt: $endEventIndex }
        ]
      }
      orderBy: eventIndex
      orderDirection: desc
      first: $limit
    ) {
      ...ForceBuyBackData
    }
    minimumDepositUpdateRecords(
      where: {
        and: [
          $minimumDepositUpdateRecordsFilter
          { eventIndex_gte: $startEventIndex, eventIndex_lt: $endEventIndex }
        ]
      }
      orderBy: eventIndex
      orderDirection: desc
      first: $limit
    ) {
      ...MinimumDepositUpdatedData
    }
    protocolFeeBipsUpdatedRecords(
      where: {
        and: [
          $protocolFeeBipsUpdatedRecordsFilter
          { eventIndex_gte: $startEventIndex, eventIndex_lt: $endEventIndex }
        ]
      }
      orderBy: eventIndex
      orderDirection: desc
      first: $limit
    ) {
      ...ProtocolFeeBipsUpdatedData
    }
    fixedTermUpdatedRecords(
      where: {
        and: [
          $fixedTermUpdatedRecordsFilter
          { eventIndex_gte: $startEventIndex, eventIndex_lt: $endEventIndex }
        ]
      }
      orderBy: eventIndex
      orderDirection: desc
      first: $limit
    ) {
      ...FixedTermUpdatedData
    }
    periodicTermUpdatedRecords(
      where: {
        and: [
          $periodicTermUpdatedRecordsFilter
          { eventIndex_gte: $startEventIndex, eventIndex_lt: $endEventIndex }
        ]
      }
      orderBy: eventIndex
      orderDirection: desc
      first: $limit
    ) {
      ...PeriodicTermUpdatedData
    }
    annualInterestBipsReductionProposalRecords(
      where: {
        and: [
          $annualInterestBipsReductionProposalRecordsFilter
          { eventIndex_gte: $startEventIndex, eventIndex_lt: $endEventIndex }
        ]
      }
      orderBy: eventIndex
      orderDirection: desc
      first: $limit
    ) {
      ...AnnualInterestBipsReductionProposedData
    }
  }
}

# ---------------------------------------------------------------------------- #
#                                Borrower Views                                #
# ---------------------------------------------------------------------------- #

query getMarketsWithEvents(
  $marketFilter: Market_filter = { id_not: null }
  $shouldSkipRecords: Boolean = false
  # markets - default order is newest first
  $numMarkets: Int = 1000
  $skipMarkets: Int = 0
  $orderMarkets: Market_orderBy = createdAt
  $directionMarkets: OrderDirection = desc
  # deposits
  $numDeposits: Int = 10
  $skipDeposits: Int = 0
  $orderDeposits: Deposit_orderBy = blockTimestamp
  $directionDeposits: OrderDirection = desc
  # borrowRecords
  $numBorrows: Int = 10
  $skipBorrows: Int = 0
  $orderBorrows: Borrow_orderBy = blockTimestamp
  $directionBorrows: OrderDirection = desc
  # feeCollections
  $numFeeCollections: Int = 10
  $skipFeeCollections: Int = 0
  $orderFeeCollections: FeesCollected_orderBy = blockTimestamp
  $directionFeeCollections: OrderDirection = desc
  # repaymentRecords
  $numRepayments: Int = 10
  $skipRepayments: Int = 0
  $orderRepayments: DebtRepaid_orderBy = blockTimestamp
  $directionRepayments: OrderDirection = desc
) {
  markets(
    where: $marketFilter
    orderBy: $orderMarkets
    orderDirection: $directionMarkets
    first: $numMarkets
    skip: $skipMarkets
  ) {
    ...MarketDataWithEvents
  }
}

query getMarket(
  $market: ID!
  $shouldSkipRecords: Boolean = false
  # deposits
  $numDeposits: Int = 10
  $skipDeposits: Int = 0
  $orderDeposits: Deposit_orderBy = blockTimestamp
  $directionDeposits: OrderDirection = desc
  # borrowRecords
  $numBorrows: Int = 10
  $skipBorrows: Int = 0
  $orderBorrows: Borrow_orderBy = blockTimestamp
  $directionBorrows: OrderDirection = desc
  # feeCollections
  $numFeeCollections: Int = 10
  $skipFeeCollections: Int = 0
  $orderFeeCollections: FeesCollected_orderBy = blockTimestamp
  $directionFeeCollections: OrderDirection = desc
  # repaymentRecords
  $numRepayments: Int = 10
  $skipRepayments: Int = 0
  $orderRepayments: DebtRepaid_orderBy = blockTimestamp
  $directionRepayments: OrderDirection = desc
) {
  market(id: $market) {
    ...MarketDataWithEvents
  }
}

query getWithdrawalRequestsByMarket(
  $market: String!
  $numWithdrawals: Int = 1000
  $skipWithdrawals: Int = 0
  $orderWithdrawals: WithdrawalRequest_orderBy = blockTimestamp
  $directionWithdrawals: OrderDirection = desc
) {
  withdrawalRequests(
    orderBy: $orderWithdrawals
    orderDirection: $directionWithdrawals
    first: $numWithdrawals
    skip: $skipWithdrawals
    where: { batch_contains_nocase: $market }
  ) {
    ...WithdrawalRequestProperties
  }
}

query getAllPendingWithdrawalBatchesForMarket($market: ID!) {
  market(id: $market) {
    withdrawalBatches(where: { isClosed: false }) {
      ...WithdrawalBatchPropertiesWithEvents
    }
  }
}

query getIncompleteWithdrawalsForMarket(
  $market: ID!
  $numWithdrawalBatches: Int = 100
  $skipWithdrawalBatches: Int = 0
  $orderWithdrawalBatches: WithdrawalBatch_orderBy = expiry
  $directionWithdrawalBatches: OrderDirection = desc
) {
  market(id: $market) {
    withdrawalBatches(
      orderBy: $orderWithdrawalBatches
      orderDirection: $directionWithdrawalBatches
      first: $numWithdrawalBatches
      skip: $skipWithdrawalBatches
      where: { isCompleted: false }
    ) {
      ...WithdrawalBatchPropertiesWithEvents
    }
  }
}

query getAllMarkets {
  markets {
    ...MarketData
  }
}

query getMarketList(
  $marketFilter: Market_filter = { id_not: null }
  $numMarkets: Int = 1000
  $skipMarkets: Int = 0
  $orderMarkets: Market_orderBy = createdAt
  $directionMarkets: OrderDirection = desc
) {
  markets(
    where: $marketFilter
    orderBy: $orderMarkets
    orderDirection: $directionMarkets
    first: $numMarkets
    skip: $skipMarkets
  ) {
    ...MarketListData
  }
}

query getAuthorizedLendersByMarket($market: ID!) {
  market(id: $market) {
    controller {
      authorizedLenders {
        lender
        authorized
        changes(first: 1, orderBy: blockTimestamp, orderDirection: desc) {
          blockTimestamp
        }
      }
    }
    lenders {
      address
      scaledBalance
      role
    }
  }
}

query getAllAuthorizedLenders($borrower: Bytes!) {
  markets(where: { borrower: $borrower, isClosed: false }) {
    id
    name

    controller {
      authorizedLenders {
        ...AllAuthorizedLendersView
      }
    }
    hooks {
      lenders {
        ...LenderHooksAccessData
      }
    }
  }
}

query getV1AuthorizedLenders(
  $borrower: Bytes!
  # markets - default order is newest first
  $numMarkets: Int = 1000
  $skipMarkets: Int = 0
  $orderMarkets: Market_orderBy = createdAt
  $directionMarkets: OrderDirection = desc
) {
  controllers(where: { borrower: $borrower }, first: 1) {
    markets(
      where: { borrower: $borrower, isClosed: false, version: V2 }
      first: $numMarkets
      skip: $skipMarkets
      orderBy: $orderMarkets
      orderDirection: $directionMarkets
    ) {
      id
      name
    }

    authorizedLenders {
      lender
      authorized
    }
  }
}

fragment V1LenderWithActiveMarkets on LenderAuthorization {
  lender
  authorized
  addedTimestamp
  marketAccounts(first: $numMarketAccountsPerLender, skip: $skipMarketAccountsPerLender) {
    role
    market {
      id
      name
    }
  }
}

fragment V2LenderWithActiveMarkets on LenderHooksAccess {
  ...LenderHooksAccessData

  addedTimestamp
  marketAccounts(first: $numMarketAccountsPerLender, skip: $skipMarketAccountsPerLender) {
    knownLenderStatus {
      id
    }
    market {
      id
      name
    }
  }
}

fragment ControllerAuthorizedLendersWithActiveMarkets on Controller {
  authorizedLenders(first: $numLenders, skip: $skipLenders, where: $lenderAuthorizationFilter) {
    ...V1LenderWithActiveMarkets
  }
}

fragment HooksInstanceLendersWithActiveMarkets on HooksInstance {
  lenders(
    first: $numLenders
    skip: $skipLenders
    orderBy: $orderLenderHooksAccess
    orderDirection: $directionLenders
    where: $lenderHooksAccessFilter
  ) {
    ...V2LenderWithActiveMarkets
  }
}

# For a given controller or hooks instance, this query should return:
# - hooks instance details if it is a hooks instance
# - all lenders with a credential (past or current) on said contract with:
#   - the source of the credential for V2 markets
#   - active markets for the lender
query getLendersByHooksInstanceOrController(
  $contractAddress: ID!
  $isController: Boolean!
  # authorized lenders
  $lenderHooksAccessFilter: LenderHooksAccess_filter = { id_not: null } # for V2
  $lenderAuthorizationFilter: LenderAuthorization_filter = { id_not: null } # for V1
  $numMarketAccountsPerLender: Int = 100
  $skipMarketAccountsPerLender: Int = 0
  $numLenders: Int = 1000
  $skipLenders: Int = 0
  $orderLenderHooksAccess: LenderHooksAccess_orderBy = lastApprovalTimestamp # for V2
  $directionLenders: OrderDirection = desc # for V1 or V2
) {
  hooksInstance(id: $contractAddress) @skip(if: $isController) {
    ...HooksInstanceData
    ...HooksInstanceLendersWithActiveMarkets
  }
  controller(id: $contractAddress) @include(if: $isController) {
    ...ControllerAuthorizedLendersWithActiveMarkets
  }
}

# For a given controller or hooks instance, this query should return:
# - hooks instance details if it is a hooks instance
# - all markets for the given contract
# - all lenders with a credential (past or current) on said contract with:
#   - the source of the credential for V2 markets
#   - active markets for the lender
query getMarketsAndLendersByHooksInstanceOrController(
  $contractAddress: ID!
  # markets
  $marketFilter: Market_filter = { id_not: null }
  $numMarkets: Int = 1000
  $skipMarkets: Int = 0
  $orderMarkets: Market_orderBy = createdAt
  $directionMarkets: OrderDirection = desc
  # authorized lenders
  $lenderHooksAccessFilter: LenderHooksAccess_filter = { id_not: null } # for V2
  $lenderAuthorizationFilter: LenderAuthorization_filter = { id_not: null } # for V1
  $numMarketAccountsPerLender: Int = 100
  $skipMarketAccountsPerLender: Int = 0
  $numLenders: Int = 1000
  $skipLenders: Int = 0
  $orderLenderHooksAccess: LenderHooksAccess_orderBy = lastApprovalTimestamp # for V2
  $directionLenders: OrderDirection = desc # for V1 or V2
) {
  hooksInstance(id: $contractAddress) {
    ...HooksInstanceData
    markets(
      where: $marketFilter
      first: $numMarkets
      skip: $skipMarkets
      orderBy: $orderMarkets
      orderDirection: $directionMarkets
    ) {
      ...MarketData
    }
    ...HooksInstanceLendersWithActiveMarkets
  }
  controller(id: $contractAddress) {
    ...MinimalControllerData
    markets(
      where: $marketFilter
      first: $numMarkets
      skip: $skipMarkets
      orderBy: $orderMarkets
      orderDirection: $directionMarkets
    ) {
      ...MarketData
    }
    ...ControllerAuthorizedLendersWithActiveMarkets
  }
}

# For a given market, get all active lenders with their:
# address
# balance (and info needed to derive balance with interest)
# v1 / v2 access level info
query getActiveLendersByMarket(
  $market: ID!
  $accountFilter: LenderAccount_filter = { address_not: null }
  $numAccounts: Int = 1000
  $skipAccounts: Int = 0
  $orderAccounts: LenderAccount_orderBy = lastUpdatedTimestamp
  $directionAccounts: OrderDirection = desc
) {
  market(id: $market) {
    lenders(
      where: $accountFilter
      first: $numAccounts
      skip: $skipAccounts
      orderBy: $orderAccounts
      orderDirection: $directionAccounts
    ) {
      ...BasicLenderData
    }
  }
}

query getAuthorizedLendersByBorrower($filter: Controller_filter!) {
  controllers(where: $filter) {
    authorizedLenders(where: { authorized: true }) {
      lender
    }
  }
}

query getSubgraphStatus {
  _meta {
    hasIndexingErrors
    block {
      hash
      number
      timestamp
    }
  }
}

query getMarketRecords(
  $market: ID!
  # deposits
  $numDeposits: Int = 10
  $skipDeposits: Int = 0
  $orderDeposits: Deposit_orderBy = blockTimestamp
  $directionDeposits: OrderDirection = desc
  # borrowRecords
  $numBorrows: Int = 10
  $skipBorrows: Int = 0
  $orderBorrows: Borrow_orderBy = blockTimestamp
  $directionBorrows: OrderDirection = desc
  # feeCollections
  $numFeeCollections: Int = 10
  $skipFeeCollections: Int = 0
  $orderFeeCollections: FeesCollected_orderBy = blockTimestamp
  $directionFeeCollections: OrderDirection = desc
  # repaymentRecords
  $numRepayments: Int = 10
  $skipRepayments: Int = 0
  $orderRepayments: DebtRepaid_orderBy = blockTimestamp
  $directionRepayments: OrderDirection = desc
) {
  market(id: $market) {
    ...MarketRecords
  }
}

query getAllTokensWithMarkets {
  tokens {
    address
    name
    symbol
    decimals
  }
}

query getCollateralContractsByMarket($market: ID!) {
  market(id: $market) {
    collateralContracts {
      ...SimpleCollateralContractData
    }
  }
}

query getCollateralContract($collateralContract: ID!) {
  simpleCollateralContract(id: $collateralContract) {
    ...SimpleCollateralContractData
  }
}

query getApprovedLiquidators {
  approvedLiquidators(where: { isApproved: true }) {
    liquidator
  }
}

query getCollateralContractEvents(
  $collateralContract: ID!
  $startEventIndex: Int = 0
  $endEventIndex: Int = 100000000
  $limit: Int = 10
  $depositRecordsFilter: SimpleCollateralContractDeposit_filter = { id_not: null }
  $includeDeposits: Boolean = true
  $reclaimRecordsFilter: SimpleCollateralContractReclaim_filter = { id_not: null }
  $includeReclaims: Boolean = true
  $liquidationRecordsFilter: SimpleCollateralContractLiquidation_filter = { id_not: null }
  $includeLiquidations: Boolean = true
  $fullResetRecordsFilter: SimpleCollateralContractFullReset_filter = { id_not: null }
  $includeFullResets: Boolean = true
  $liquidatedSharesResetRecordsFilter: SimpleCollateralContractLiquidatedSharesReset_filter = { id_not: null }
  $includeLiquidatedSharesResets: Boolean = true
) {
  simpleCollateralContract(id: $collateralContract) {
    deposits(
      where: {
        and: [
          $depositRecordsFilter
          { eventIndex_gte: $startEventIndex, eventIndex_lt: $endEventIndex }
        ]
      }
      orderBy: eventIndex
      orderDirection: desc
      first: $limit
    ) @include(if: $includeDeposits) {
      ...SimpleCollateralContractDepositData
    } 
    reclaims(
      where: {
        and: [
          $reclaimRecordsFilter
          { eventIndex_gte: $startEventIndex, eventIndex_lt: $endEventIndex }
        ]
      }
      orderBy: eventIndex
      orderDirection: desc
      first: $limit
    ) @include(if: $includeReclaims) {
      ...SimpleCollateralContractReclaimData
    }
    liquidations(
      where: {
        and: [
          $liquidationRecordsFilter
          { eventIndex_gte: $startEventIndex, eventIndex_lt: $endEventIndex }
        ]
      }
      orderBy: eventIndex
      orderDirection: desc
      first: $limit
    ) @include(if: $includeLiquidations) {
      ...SimpleCollateralContractLiquidationData
    }
    fullResets(
      where: {
        and: [
          $fullResetRecordsFilter
          { eventIndex_gte: $startEventIndex, eventIndex_lt: $endEventIndex }
        ]
      }
      orderBy: eventIndex
      orderDirection: desc
      first: $limit
    ) @include(if: $includeFullResets) {
      ...SimpleCollateralContractFullResetData
    }
    liquidatedSharesResets(
      where: {
        and: [
          $liquidatedSharesResetRecordsFilter
          { eventIndex_gte: $startEventIndex, eventIndex_lt: $endEventIndex }
        ]
      }
      orderBy: eventIndex
      orderDirection: desc
      first: $limit
    ) @include(if: $includeLiquidatedSharesResets) {
      ...SimpleCollateralContractLiquidatedSharesResetData
    }
  }
}

query getMarketChartsData(
  $market: ID!
  # withdrawal batches
  $numWithdrawalBatches: Int = 100
  $skipWithdrawalBatches: Int = 0
  $orderWithdrawalBatches: WithdrawalBatch_orderBy = expiry
  $directionWithdrawalBatches: OrderDirection = desc
  # daily stats
  $numDailyStats: Int = 100
  $skipDailyStats: Int = 0
  $orderDailyStats: MarketDailyStats_orderBy = startTimestamp
  $directionDailyStats: OrderDirection = desc
) {
  market(id: $market) {
    # Only expired withdrawal batches
    withdrawalBatches(
      where: { expiration_: { id_not: null } }
      first: $numWithdrawalBatches
      skip: $skipWithdrawalBatches
      orderBy: $orderWithdrawalBatches
      orderDirection: $directionWithdrawalBatches
    ) {
      expiry
      expiration {
        normalizedAmountPaid
        normalizedAmountOwed
      }
    }
    asset {
      decimals
      symbol
      name
    }
    dailyStats(
      first: $numDailyStats
      skip: $skipDailyStats
      orderBy: $orderDailyStats
      orderDirection: $directionDailyStats
    ) {
      timestamp: startTimestamp
      totalDeposited
      totalWithdrawalsRequested
      totalBorrowed
      totalRepaid
    }
  }
}
