/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type AccountDescriptionStruct = {
  kind: PromiseOrValue<BigNumberish>;
  owners: PromiseOrValue<string>[];
  threshold: PromiseOrValue<BigNumberish>;
};

export type AccountDescriptionStructOutput = [number, string[], BigNumber] & {
  kind: number;
  owners: string[];
  threshold: BigNumber;
};

export interface AccountsQueryInterface extends utils.Interface {
  functions: {
    "describeAccounts(address[])": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "describeAccounts"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "describeAccounts",
    values: [PromiseOrValue<string>[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "describeAccounts",
    data: BytesLike
  ): Result;

  events: {};
}

export interface AccountsQuery extends BaseContract {
  contractName: "AccountsQuery";

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AccountsQueryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    describeAccounts(
      account: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<[AccountDescriptionStructOutput[]]>;
  };

  describeAccounts(
    account: PromiseOrValue<string>[],
    overrides?: CallOverrides
  ): Promise<AccountDescriptionStructOutput[]>;

  callStatic: {
    describeAccounts(
      account: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<AccountDescriptionStructOutput[]>;
  };

  filters: {};

  estimateGas: {
    describeAccounts(
      account: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    describeAccounts(
      account: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
