/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type HookedMarketStruct = {
  isHooked: PromiseOrValue<boolean>;
  transferRequiresAccess: PromiseOrValue<boolean>;
  depositRequiresAccess: PromiseOrValue<boolean>;
  minimumDeposit: PromiseOrValue<BigNumberish>;
  transfersDisabled: PromiseOrValue<boolean>;
  allowForceBuyBacks: PromiseOrValue<boolean>;
};

export type HookedMarketStructOutput = {
  isHooked: boolean;
  transferRequiresAccess: boolean;
  depositRequiresAccess: boolean;
  minimumDeposit: BigNumber;
  transfersDisabled: boolean;
  allowForceBuyBacks: boolean;
};

export type LenderStatusStruct = {
  isBlockedFromDeposits: PromiseOrValue<boolean>;
  lastProvider: PromiseOrValue<string>;
  canRefresh: PromiseOrValue<boolean>;
  lastApprovalTimestamp: PromiseOrValue<BigNumberish>;
};

export type LenderStatusStructOutput = {
  isBlockedFromDeposits: boolean;
  lastProvider: string;
  canRefresh: boolean;
  lastApprovalTimestamp: number;
};

export type MarketParameterConstraintsStruct = {
  minimumDelinquencyGracePeriod: PromiseOrValue<BigNumberish>;
  maximumDelinquencyGracePeriod: PromiseOrValue<BigNumberish>;
  minimumReserveRatioBips: PromiseOrValue<BigNumberish>;
  maximumReserveRatioBips: PromiseOrValue<BigNumberish>;
  minimumDelinquencyFeeBips: PromiseOrValue<BigNumberish>;
  maximumDelinquencyFeeBips: PromiseOrValue<BigNumberish>;
  minimumWithdrawalBatchDuration: PromiseOrValue<BigNumberish>;
  maximumWithdrawalBatchDuration: PromiseOrValue<BigNumberish>;
  minimumAnnualInterestBips: PromiseOrValue<BigNumberish>;
  maximumAnnualInterestBips: PromiseOrValue<BigNumberish>;
};

export type MarketParameterConstraintsStructOutput = {
  minimumDelinquencyGracePeriod: number;
  maximumDelinquencyGracePeriod: number;
  minimumReserveRatioBips: number;
  maximumReserveRatioBips: number;
  minimumDelinquencyFeeBips: number;
  maximumDelinquencyFeeBips: number;
  minimumWithdrawalBatchDuration: number;
  maximumWithdrawalBatchDuration: number;
  minimumAnnualInterestBips: number;
  maximumAnnualInterestBips: number;
};

export type MarketStateV2Struct = {
  isClosed: PromiseOrValue<boolean>;
  maxTotalSupply: PromiseOrValue<BigNumberish>;
  accruedProtocolFees: PromiseOrValue<BigNumberish>;
  normalizedUnclaimedWithdrawals: PromiseOrValue<BigNumberish>;
  scaledTotalSupply: PromiseOrValue<BigNumberish>;
  scaledPendingWithdrawals: PromiseOrValue<BigNumberish>;
  pendingWithdrawalExpiry: PromiseOrValue<BigNumberish>;
  isDelinquent: PromiseOrValue<boolean>;
  timeDelinquent: PromiseOrValue<BigNumberish>;
  protocolFeeBips: PromiseOrValue<BigNumberish>;
  annualInterestBips: PromiseOrValue<BigNumberish>;
  reserveRatioBips: PromiseOrValue<BigNumberish>;
  scaleFactor: PromiseOrValue<BigNumberish>;
  lastInterestAccruedTimestamp: PromiseOrValue<BigNumberish>;
};

export type MarketStateV2StructOutput = {
  isClosed: boolean;
  maxTotalSupply: BigNumber;
  accruedProtocolFees: BigNumber;
  normalizedUnclaimedWithdrawals: BigNumber;
  scaledTotalSupply: BigNumber;
  scaledPendingWithdrawals: BigNumber;
  pendingWithdrawalExpiry: number;
  isDelinquent: boolean;
  timeDelinquent: number;
  protocolFeeBips: number;
  annualInterestBips: number;
  reserveRatioBips: number;
  scaleFactor: BigNumber;
  lastInterestAccruedTimestamp: number;
};

export type DeployMarketInputsV2Struct = {
  asset: PromiseOrValue<string>;
  namePrefix: PromiseOrValue<string>;
  symbolPrefix: PromiseOrValue<string>;
  maxTotalSupply: PromiseOrValue<BigNumberish>;
  annualInterestBips: PromiseOrValue<BigNumberish>;
  delinquencyFeeBips: PromiseOrValue<BigNumberish>;
  withdrawalBatchDuration: PromiseOrValue<BigNumberish>;
  reserveRatioBips: PromiseOrValue<BigNumberish>;
  delinquencyGracePeriod: PromiseOrValue<BigNumberish>;
  hooks: PromiseOrValue<BigNumberish>;
};

export type DeployMarketInputsV2StructOutput = {
  asset: string;
  namePrefix: string;
  symbolPrefix: string;
  maxTotalSupply: BigNumber;
  annualInterestBips: number;
  delinquencyFeeBips: number;
  withdrawalBatchDuration: number;
  reserveRatioBips: number;
  delinquencyGracePeriod: number;
  hooks: BigNumber;
};

export interface IOpenTermHooksInterface extends utils.Interface {
  functions: {
    "addRoleProvider(address,uint32)": FunctionFragment;
    "blockFromDeposits(address)": FunctionFragment;
    "borrower()": FunctionFragment;
    "config()": FunctionFragment;
    "createRoleProvider(address,uint32,bytes)": FunctionFragment;
    "disableForceBuyBacks(address)": FunctionFragment;
    "factory()": FunctionFragment;
    "getHookedMarket(address)": FunctionFragment;
    "getHookedMarkets(address[])": FunctionFragment;
    "getLenderStatus(address)": FunctionFragment;
    "getParameterConstraints()": FunctionFragment;
    "getPreviousLenderStatus(address)": FunctionFragment;
    "getPullProviders()": FunctionFragment;
    "getPushProviders()": FunctionFragment;
    "getRoleProvider(address)": FunctionFragment;
    "grantRole(address,uint32)": FunctionFragment;
    "grantRoles(address[],uint32[])": FunctionFragment;
    "isKnownLenderOnMarket(address,address)": FunctionFragment;
    "name()": FunctionFragment;
    "onBorrow(uint256,(bool,uint128,uint128,uint128,uint104,uint104,uint32,bool,uint32,uint16,uint16,uint16,uint112,uint32),bytes)": FunctionFragment;
    "onCloseMarket((bool,uint128,uint128,uint128,uint104,uint104,uint32,bool,uint32,uint16,uint16,uint16,uint112,uint32),bytes)": FunctionFragment;
    "onCreateMarket(address,address,(address,string,string,uint128,uint16,uint16,uint32,uint16,uint32,uint256),bytes)": FunctionFragment;
    "onDeposit(address,uint256,(bool,uint128,uint128,uint128,uint104,uint104,uint32,bool,uint32,uint16,uint16,uint16,uint112,uint32),bytes)": FunctionFragment;
    "onExecuteWithdrawal(address,uint128,(bool,uint128,uint128,uint128,uint104,uint104,uint32,bool,uint32,uint16,uint16,uint16,uint112,uint32),bytes)": FunctionFragment;
    "onForceBuyBack(address,uint256,(bool,uint128,uint128,uint128,uint104,uint104,uint32,bool,uint32,uint16,uint16,uint16,uint112,uint32),bytes)": FunctionFragment;
    "onNukeFromOrbit(address,(bool,uint128,uint128,uint128,uint104,uint104,uint32,bool,uint32,uint16,uint16,uint16,uint112,uint32),bytes)": FunctionFragment;
    "onQueueWithdrawal(address,uint32,uint256,(bool,uint128,uint128,uint128,uint104,uint104,uint32,bool,uint32,uint16,uint16,uint16,uint112,uint32),bytes)": FunctionFragment;
    "onRepay(uint256,(bool,uint128,uint128,uint128,uint104,uint104,uint32,bool,uint32,uint16,uint16,uint16,uint112,uint32),bytes)": FunctionFragment;
    "onSetAnnualInterestAndReserveRatioBips(uint16,uint16,(bool,uint128,uint128,uint128,uint104,uint104,uint32,bool,uint32,uint16,uint16,uint16,uint112,uint32),bytes)": FunctionFragment;
    "onSetMaxTotalSupply(uint256,(bool,uint128,uint128,uint128,uint104,uint104,uint32,bool,uint32,uint16,uint16,uint16,uint112,uint32),bytes)": FunctionFragment;
    "onSetProtocolFeeBips(uint16,(bool,uint128,uint128,uint128,uint104,uint104,uint32,bool,uint32,uint16,uint16,uint16,uint112,uint32),bytes)": FunctionFragment;
    "onTransfer(address,address,address,uint256,(bool,uint128,uint128,uint128,uint104,uint104,uint32,bool,uint32,uint16,uint16,uint16,uint112,uint32),bytes)": FunctionFragment;
    "removeRoleProvider(address)": FunctionFragment;
    "revokeRole(address)": FunctionFragment;
    "setMinimumDeposit(address,uint128)": FunctionFragment;
    "setName(string)": FunctionFragment;
    "temporaryExcessReserveRatio(address)": FunctionFragment;
    "unblockFromDeposits(address)": FunctionFragment;
    "version()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addRoleProvider"
      | "blockFromDeposits"
      | "borrower"
      | "config"
      | "createRoleProvider"
      | "disableForceBuyBacks"
      | "factory"
      | "getHookedMarket"
      | "getHookedMarkets"
      | "getLenderStatus"
      | "getParameterConstraints"
      | "getPreviousLenderStatus"
      | "getPullProviders"
      | "getPushProviders"
      | "getRoleProvider"
      | "grantRole"
      | "grantRoles"
      | "isKnownLenderOnMarket"
      | "name"
      | "onBorrow"
      | "onCloseMarket"
      | "onCreateMarket"
      | "onDeposit"
      | "onExecuteWithdrawal"
      | "onForceBuyBack"
      | "onNukeFromOrbit"
      | "onQueueWithdrawal"
      | "onRepay"
      | "onSetAnnualInterestAndReserveRatioBips"
      | "onSetMaxTotalSupply"
      | "onSetProtocolFeeBips"
      | "onTransfer"
      | "removeRoleProvider"
      | "revokeRole"
      | "setMinimumDeposit"
      | "setName"
      | "temporaryExcessReserveRatio"
      | "unblockFromDeposits"
      | "version"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addRoleProvider",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "blockFromDeposits",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "borrower", values?: undefined): string;
  encodeFunctionData(functionFragment: "config", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createRoleProvider",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "disableForceBuyBacks",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getHookedMarket",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getHookedMarkets",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getLenderStatus",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getParameterConstraints",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPreviousLenderStatus",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPullProviders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPushProviders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleProvider",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRoles",
    values: [PromiseOrValue<string>[], PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isKnownLenderOnMarket",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onBorrow",
    values: [
      PromiseOrValue<BigNumberish>,
      MarketStateV2Struct,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onCloseMarket",
    values: [MarketStateV2Struct, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "onCreateMarket",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      DeployMarketInputsV2Struct,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onDeposit",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      MarketStateV2Struct,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onExecuteWithdrawal",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      MarketStateV2Struct,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onForceBuyBack",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      MarketStateV2Struct,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onNukeFromOrbit",
    values: [
      PromiseOrValue<string>,
      MarketStateV2Struct,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onQueueWithdrawal",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      MarketStateV2Struct,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onRepay",
    values: [
      PromiseOrValue<BigNumberish>,
      MarketStateV2Struct,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onSetAnnualInterestAndReserveRatioBips",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      MarketStateV2Struct,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onSetMaxTotalSupply",
    values: [
      PromiseOrValue<BigNumberish>,
      MarketStateV2Struct,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onSetProtocolFeeBips",
    values: [
      PromiseOrValue<BigNumberish>,
      MarketStateV2Struct,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onTransfer",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      MarketStateV2Struct,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "removeRoleProvider",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinimumDeposit",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setName",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "temporaryExcessReserveRatio",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "unblockFromDeposits",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "addRoleProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blockFromDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "borrower", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "config", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createRoleProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disableForceBuyBacks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getHookedMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHookedMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLenderStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParameterConstraints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPreviousLenderStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPullProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPushProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grantRoles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isKnownLenderOnMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "onBorrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onCloseMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onCreateMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "onDeposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onExecuteWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onForceBuyBack",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onNukeFromOrbit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onQueueWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "onRepay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onSetAnnualInterestAndReserveRatioBips",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onSetMaxTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onSetProtocolFeeBips",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "onTransfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeRoleProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMinimumDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "temporaryExcessReserveRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unblockFromDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;

  events: {
    "AccountAccessGranted(address,address,uint32)": EventFragment;
    "AccountAccessRevoked(address)": EventFragment;
    "AccountBlockedFromDeposits(address)": EventFragment;
    "AccountMadeFirstDeposit(address,address)": EventFragment;
    "AccountUnblockedFromDeposits(address)": EventFragment;
    "DisabledForceBuyBacks(address)": EventFragment;
    "MinimumDepositUpdated(address,uint128)": EventFragment;
    "NameUpdated(string)": EventFragment;
    "RoleProviderAdded(address,uint32,uint24,uint24)": EventFragment;
    "RoleProviderRemoved(address,uint24,uint24)": EventFragment;
    "RoleProviderUpdated(address,uint32,uint24,uint24)": EventFragment;
    "TemporaryExcessReserveRatioActivated(address,uint256,uint256,uint256)": EventFragment;
    "TemporaryExcessReserveRatioCanceled(address)": EventFragment;
    "TemporaryExcessReserveRatioExpired(address)": EventFragment;
    "TemporaryExcessReserveRatioUpdated(address,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AccountAccessGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AccountAccessRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AccountBlockedFromDeposits"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AccountMadeFirstDeposit"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "AccountUnblockedFromDeposits"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DisabledForceBuyBacks"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MinimumDepositUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NameUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleProviderAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleProviderRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleProviderUpdated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "TemporaryExcessReserveRatioActivated"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "TemporaryExcessReserveRatioCanceled"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "TemporaryExcessReserveRatioExpired"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "TemporaryExcessReserveRatioUpdated"
  ): EventFragment;
}

export interface AccountAccessGrantedEventObject {
  providerAddress: string;
  accountAddress: string;
  credentialTimestamp: number;
}
export type AccountAccessGrantedEvent = TypedEvent<
  [string, string, number],
  AccountAccessGrantedEventObject
>;

export type AccountAccessGrantedEventFilter =
  TypedEventFilter<AccountAccessGrantedEvent>;

export interface AccountAccessRevokedEventObject {
  accountAddress: string;
}
export type AccountAccessRevokedEvent = TypedEvent<
  [string],
  AccountAccessRevokedEventObject
>;

export type AccountAccessRevokedEventFilter =
  TypedEventFilter<AccountAccessRevokedEvent>;

export interface AccountBlockedFromDepositsEventObject {
  accountAddress: string;
}
export type AccountBlockedFromDepositsEvent = TypedEvent<
  [string],
  AccountBlockedFromDepositsEventObject
>;

export type AccountBlockedFromDepositsEventFilter =
  TypedEventFilter<AccountBlockedFromDepositsEvent>;

export interface AccountMadeFirstDepositEventObject {
  market: string;
  accountAddress: string;
}
export type AccountMadeFirstDepositEvent = TypedEvent<
  [string, string],
  AccountMadeFirstDepositEventObject
>;

export type AccountMadeFirstDepositEventFilter =
  TypedEventFilter<AccountMadeFirstDepositEvent>;

export interface AccountUnblockedFromDepositsEventObject {
  accountAddress: string;
}
export type AccountUnblockedFromDepositsEvent = TypedEvent<
  [string],
  AccountUnblockedFromDepositsEventObject
>;

export type AccountUnblockedFromDepositsEventFilter =
  TypedEventFilter<AccountUnblockedFromDepositsEvent>;

export interface DisabledForceBuyBacksEventObject {
  market: string;
}
export type DisabledForceBuyBacksEvent = TypedEvent<
  [string],
  DisabledForceBuyBacksEventObject
>;

export type DisabledForceBuyBacksEventFilter =
  TypedEventFilter<DisabledForceBuyBacksEvent>;

export interface MinimumDepositUpdatedEventObject {
  market: string;
  newMinimumDeposit: BigNumber;
}
export type MinimumDepositUpdatedEvent = TypedEvent<
  [string, BigNumber],
  MinimumDepositUpdatedEventObject
>;

export type MinimumDepositUpdatedEventFilter =
  TypedEventFilter<MinimumDepositUpdatedEvent>;

export interface NameUpdatedEventObject {
  name: string;
}
export type NameUpdatedEvent = TypedEvent<[string], NameUpdatedEventObject>;

export type NameUpdatedEventFilter = TypedEventFilter<NameUpdatedEvent>;

export interface RoleProviderAddedEventObject {
  providerAddress: string;
  timeToLive: number;
  pullProviderIndex: number;
  pushProviderIndex: number;
}
export type RoleProviderAddedEvent = TypedEvent<
  [string, number, number, number],
  RoleProviderAddedEventObject
>;

export type RoleProviderAddedEventFilter =
  TypedEventFilter<RoleProviderAddedEvent>;

export interface RoleProviderRemovedEventObject {
  providerAddress: string;
  pullProviderIndex: number;
  pushProviderIndex: number;
}
export type RoleProviderRemovedEvent = TypedEvent<
  [string, number, number],
  RoleProviderRemovedEventObject
>;

export type RoleProviderRemovedEventFilter =
  TypedEventFilter<RoleProviderRemovedEvent>;

export interface RoleProviderUpdatedEventObject {
  providerAddress: string;
  timeToLive: number;
  pullProviderIndex: number;
  pushProviderIndex: number;
}
export type RoleProviderUpdatedEvent = TypedEvent<
  [string, number, number, number],
  RoleProviderUpdatedEventObject
>;

export type RoleProviderUpdatedEventFilter =
  TypedEventFilter<RoleProviderUpdatedEvent>;

export interface TemporaryExcessReserveRatioActivatedEventObject {
  market: string;
  originalReserveRatioBips: BigNumber;
  temporaryReserveRatioBips: BigNumber;
  temporaryReserveRatioExpiry: BigNumber;
}
export type TemporaryExcessReserveRatioActivatedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  TemporaryExcessReserveRatioActivatedEventObject
>;

export type TemporaryExcessReserveRatioActivatedEventFilter =
  TypedEventFilter<TemporaryExcessReserveRatioActivatedEvent>;

export interface TemporaryExcessReserveRatioCanceledEventObject {
  market: string;
}
export type TemporaryExcessReserveRatioCanceledEvent = TypedEvent<
  [string],
  TemporaryExcessReserveRatioCanceledEventObject
>;

export type TemporaryExcessReserveRatioCanceledEventFilter =
  TypedEventFilter<TemporaryExcessReserveRatioCanceledEvent>;

export interface TemporaryExcessReserveRatioExpiredEventObject {
  market: string;
}
export type TemporaryExcessReserveRatioExpiredEvent = TypedEvent<
  [string],
  TemporaryExcessReserveRatioExpiredEventObject
>;

export type TemporaryExcessReserveRatioExpiredEventFilter =
  TypedEventFilter<TemporaryExcessReserveRatioExpiredEvent>;

export interface TemporaryExcessReserveRatioUpdatedEventObject {
  market: string;
  originalReserveRatioBips: BigNumber;
  temporaryReserveRatioBips: BigNumber;
  temporaryReserveRatioExpiry: BigNumber;
}
export type TemporaryExcessReserveRatioUpdatedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  TemporaryExcessReserveRatioUpdatedEventObject
>;

export type TemporaryExcessReserveRatioUpdatedEventFilter =
  TypedEventFilter<TemporaryExcessReserveRatioUpdatedEvent>;

export interface IOpenTermHooks extends BaseContract {
  contractName: "IOpenTermHooks";

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IOpenTermHooksInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addRoleProvider(
      providerAddress: PromiseOrValue<string>,
      timeToLive: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    blockFromDeposits(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    borrower(overrides?: CallOverrides): Promise<[string]>;

    config(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { param0: BigNumber }>;

    createRoleProvider(
      providerFactory: PromiseOrValue<string>,
      timeToLive: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    disableForceBuyBacks(
      market: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    getHookedMarket(
      marketAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [HookedMarketStructOutput] & { param0: HookedMarketStructOutput }
    >;

    getHookedMarkets(
      marketAddresses: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<
      [HookedMarketStructOutput[]] & {
        hookedMarkets: HookedMarketStructOutput[];
      }
    >;

    getLenderStatus(
      accountAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [LenderStatusStructOutput] & { status: LenderStatusStructOutput }
    >;

    getParameterConstraints(
      overrides?: CallOverrides
    ): Promise<
      [MarketParameterConstraintsStructOutput] & {
        constraints: MarketParameterConstraintsStructOutput;
      }
    >;

    getPreviousLenderStatus(
      accountAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [LenderStatusStructOutput] & { status: LenderStatusStructOutput }
    >;

    getPullProviders(
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { param0: BigNumber[] }>;

    getPushProviders(
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { param0: BigNumber[] }>;

    getRoleProvider(
      providerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { param0: BigNumber }>;

    grantRole(
      account: PromiseOrValue<string>,
      roleGrantedTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    grantRoles(
      accounts: PromiseOrValue<string>[],
      roleGrantedTimestamps: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isKnownLenderOnMarket(
      key0: PromiseOrValue<string>,
      key1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    onBorrow(
      param0: PromiseOrValue<BigNumberish>,
      param1: MarketStateV2Struct,
      param2: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    onCloseMarket(
      param0: MarketStateV2Struct,
      param1: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    onCreateMarket(
      deployer: PromiseOrValue<string>,
      marketAddress: PromiseOrValue<string>,
      parameters: DeployMarketInputsV2Struct,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    onDeposit(
      lender: PromiseOrValue<string>,
      scaledAmount: PromiseOrValue<BigNumberish>,
      state: MarketStateV2Struct,
      hooksData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    onExecuteWithdrawal(
      lender: PromiseOrValue<string>,
      param1: PromiseOrValue<BigNumberish>,
      param2: MarketStateV2Struct,
      hooksData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    onForceBuyBack(
      param0: PromiseOrValue<string>,
      param1: PromiseOrValue<BigNumberish>,
      param2: MarketStateV2Struct,
      param3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    onNukeFromOrbit(
      param0: PromiseOrValue<string>,
      param1: MarketStateV2Struct,
      param2: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    onQueueWithdrawal(
      lender: PromiseOrValue<string>,
      param1: PromiseOrValue<BigNumberish>,
      param2: PromiseOrValue<BigNumberish>,
      param3: MarketStateV2Struct,
      hooksData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    onRepay(
      normalizedAmount: PromiseOrValue<BigNumberish>,
      state: MarketStateV2Struct,
      hooksData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    onSetAnnualInterestAndReserveRatioBips(
      annualInterestBips: PromiseOrValue<BigNumberish>,
      reserveRatioBips: PromiseOrValue<BigNumberish>,
      intermediateState: MarketStateV2Struct,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    onSetMaxTotalSupply(
      param0: PromiseOrValue<BigNumberish>,
      param1: MarketStateV2Struct,
      param2: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    onSetProtocolFeeBips(
      param0: PromiseOrValue<BigNumberish>,
      param1: MarketStateV2Struct,
      param2: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    onTransfer(
      param0: PromiseOrValue<string>,
      param1: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      param3: PromiseOrValue<BigNumberish>,
      param4: MarketStateV2Struct,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeRoleProvider(
      providerAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMinimumDeposit(
      market: PromiseOrValue<string>,
      newMinimumDeposit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setName(
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    temporaryExcessReserveRatio(
      key0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [number, number, number] & {
        originalAnnualInterestBips: number;
        originalReserveRatioBips: number;
        expiry: number;
      }
    >;

    unblockFromDeposits(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    version(overrides?: CallOverrides): Promise<[string] & { param0: string }>;
  };

  addRoleProvider(
    providerAddress: PromiseOrValue<string>,
    timeToLive: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  blockFromDeposits(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  borrower(overrides?: CallOverrides): Promise<string>;

  config(overrides?: CallOverrides): Promise<BigNumber>;

  createRoleProvider(
    providerFactory: PromiseOrValue<string>,
    timeToLive: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  disableForceBuyBacks(
    market: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  factory(overrides?: CallOverrides): Promise<string>;

  getHookedMarket(
    marketAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<HookedMarketStructOutput>;

  getHookedMarkets(
    marketAddresses: PromiseOrValue<string>[],
    overrides?: CallOverrides
  ): Promise<HookedMarketStructOutput[]>;

  getLenderStatus(
    accountAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<LenderStatusStructOutput>;

  getParameterConstraints(
    overrides?: CallOverrides
  ): Promise<MarketParameterConstraintsStructOutput>;

  getPreviousLenderStatus(
    accountAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<LenderStatusStructOutput>;

  getPullProviders(overrides?: CallOverrides): Promise<BigNumber[]>;

  getPushProviders(overrides?: CallOverrides): Promise<BigNumber[]>;

  getRoleProvider(
    providerAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  grantRole(
    account: PromiseOrValue<string>,
    roleGrantedTimestamp: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  grantRoles(
    accounts: PromiseOrValue<string>[],
    roleGrantedTimestamps: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isKnownLenderOnMarket(
    key0: PromiseOrValue<string>,
    key1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  name(overrides?: CallOverrides): Promise<string>;

  onBorrow(
    param0: PromiseOrValue<BigNumberish>,
    param1: MarketStateV2Struct,
    param2: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  onCloseMarket(
    param0: MarketStateV2Struct,
    param1: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  onCreateMarket(
    deployer: PromiseOrValue<string>,
    marketAddress: PromiseOrValue<string>,
    parameters: DeployMarketInputsV2Struct,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  onDeposit(
    lender: PromiseOrValue<string>,
    scaledAmount: PromiseOrValue<BigNumberish>,
    state: MarketStateV2Struct,
    hooksData: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  onExecuteWithdrawal(
    lender: PromiseOrValue<string>,
    param1: PromiseOrValue<BigNumberish>,
    param2: MarketStateV2Struct,
    hooksData: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  onForceBuyBack(
    param0: PromiseOrValue<string>,
    param1: PromiseOrValue<BigNumberish>,
    param2: MarketStateV2Struct,
    param3: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  onNukeFromOrbit(
    param0: PromiseOrValue<string>,
    param1: MarketStateV2Struct,
    param2: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  onQueueWithdrawal(
    lender: PromiseOrValue<string>,
    param1: PromiseOrValue<BigNumberish>,
    param2: PromiseOrValue<BigNumberish>,
    param3: MarketStateV2Struct,
    hooksData: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  onRepay(
    normalizedAmount: PromiseOrValue<BigNumberish>,
    state: MarketStateV2Struct,
    hooksData: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  onSetAnnualInterestAndReserveRatioBips(
    annualInterestBips: PromiseOrValue<BigNumberish>,
    reserveRatioBips: PromiseOrValue<BigNumberish>,
    intermediateState: MarketStateV2Struct,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  onSetMaxTotalSupply(
    param0: PromiseOrValue<BigNumberish>,
    param1: MarketStateV2Struct,
    param2: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  onSetProtocolFeeBips(
    param0: PromiseOrValue<BigNumberish>,
    param1: MarketStateV2Struct,
    param2: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  onTransfer(
    param0: PromiseOrValue<string>,
    param1: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    param3: PromiseOrValue<BigNumberish>,
    param4: MarketStateV2Struct,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeRoleProvider(
    providerAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMinimumDeposit(
    market: PromiseOrValue<string>,
    newMinimumDeposit: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setName(
    _name: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  temporaryExcessReserveRatio(
    key0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [number, number, number] & {
      originalAnnualInterestBips: number;
      originalReserveRatioBips: number;
      expiry: number;
    }
  >;

  unblockFromDeposits(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  version(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    addRoleProvider(
      providerAddress: PromiseOrValue<string>,
      timeToLive: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    blockFromDeposits(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    borrower(overrides?: CallOverrides): Promise<string>;

    config(overrides?: CallOverrides): Promise<BigNumber>;

    createRoleProvider(
      providerFactory: PromiseOrValue<string>,
      timeToLive: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    disableForceBuyBacks(
      market: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    factory(overrides?: CallOverrides): Promise<string>;

    getHookedMarket(
      marketAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<HookedMarketStructOutput>;

    getHookedMarkets(
      marketAddresses: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<HookedMarketStructOutput[]>;

    getLenderStatus(
      accountAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<LenderStatusStructOutput>;

    getParameterConstraints(
      overrides?: CallOverrides
    ): Promise<MarketParameterConstraintsStructOutput>;

    getPreviousLenderStatus(
      accountAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<LenderStatusStructOutput>;

    getPullProviders(overrides?: CallOverrides): Promise<BigNumber[]>;

    getPushProviders(overrides?: CallOverrides): Promise<BigNumber[]>;

    getRoleProvider(
      providerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      account: PromiseOrValue<string>,
      roleGrantedTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    grantRoles(
      accounts: PromiseOrValue<string>[],
      roleGrantedTimestamps: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    isKnownLenderOnMarket(
      key0: PromiseOrValue<string>,
      key1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    name(overrides?: CallOverrides): Promise<string>;

    onBorrow(
      param0: PromiseOrValue<BigNumberish>,
      param1: MarketStateV2Struct,
      param2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    onCloseMarket(
      param0: MarketStateV2Struct,
      param1: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    onCreateMarket(
      deployer: PromiseOrValue<string>,
      marketAddress: PromiseOrValue<string>,
      parameters: DeployMarketInputsV2Struct,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onDeposit(
      lender: PromiseOrValue<string>,
      scaledAmount: PromiseOrValue<BigNumberish>,
      state: MarketStateV2Struct,
      hooksData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    onExecuteWithdrawal(
      lender: PromiseOrValue<string>,
      param1: PromiseOrValue<BigNumberish>,
      param2: MarketStateV2Struct,
      hooksData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    onForceBuyBack(
      param0: PromiseOrValue<string>,
      param1: PromiseOrValue<BigNumberish>,
      param2: MarketStateV2Struct,
      param3: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    onNukeFromOrbit(
      param0: PromiseOrValue<string>,
      param1: MarketStateV2Struct,
      param2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    onQueueWithdrawal(
      lender: PromiseOrValue<string>,
      param1: PromiseOrValue<BigNumberish>,
      param2: PromiseOrValue<BigNumberish>,
      param3: MarketStateV2Struct,
      hooksData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    onRepay(
      normalizedAmount: PromiseOrValue<BigNumberish>,
      state: MarketStateV2Struct,
      hooksData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    onSetAnnualInterestAndReserveRatioBips(
      annualInterestBips: PromiseOrValue<BigNumberish>,
      reserveRatioBips: PromiseOrValue<BigNumberish>,
      intermediateState: MarketStateV2Struct,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [number, number] & {
        updatedAnnualInterestBips: number;
        updatedReserveRatioBips: number;
      }
    >;

    onSetMaxTotalSupply(
      param0: PromiseOrValue<BigNumberish>,
      param1: MarketStateV2Struct,
      param2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    onSetProtocolFeeBips(
      param0: PromiseOrValue<BigNumberish>,
      param1: MarketStateV2Struct,
      param2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    onTransfer(
      param0: PromiseOrValue<string>,
      param1: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      param3: PromiseOrValue<BigNumberish>,
      param4: MarketStateV2Struct,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeRoleProvider(
      providerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMinimumDeposit(
      market: PromiseOrValue<string>,
      newMinimumDeposit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setName(
      _name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    temporaryExcessReserveRatio(
      key0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [number, number, number] & {
        originalAnnualInterestBips: number;
        originalReserveRatioBips: number;
        expiry: number;
      }
    >;

    unblockFromDeposits(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    version(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "AccountAccessGranted(address,address,uint32)"(
      providerAddress?: PromiseOrValue<string> | null,
      accountAddress?: PromiseOrValue<string> | null,
      credentialTimestamp?: null
    ): AccountAccessGrantedEventFilter;
    AccountAccessGranted(
      providerAddress?: PromiseOrValue<string> | null,
      accountAddress?: PromiseOrValue<string> | null,
      credentialTimestamp?: null
    ): AccountAccessGrantedEventFilter;

    "AccountAccessRevoked(address)"(
      accountAddress?: PromiseOrValue<string> | null
    ): AccountAccessRevokedEventFilter;
    AccountAccessRevoked(
      accountAddress?: PromiseOrValue<string> | null
    ): AccountAccessRevokedEventFilter;

    "AccountBlockedFromDeposits(address)"(
      accountAddress?: PromiseOrValue<string> | null
    ): AccountBlockedFromDepositsEventFilter;
    AccountBlockedFromDeposits(
      accountAddress?: PromiseOrValue<string> | null
    ): AccountBlockedFromDepositsEventFilter;

    "AccountMadeFirstDeposit(address,address)"(
      market?: PromiseOrValue<string> | null,
      accountAddress?: PromiseOrValue<string> | null
    ): AccountMadeFirstDepositEventFilter;
    AccountMadeFirstDeposit(
      market?: PromiseOrValue<string> | null,
      accountAddress?: PromiseOrValue<string> | null
    ): AccountMadeFirstDepositEventFilter;

    "AccountUnblockedFromDeposits(address)"(
      accountAddress?: PromiseOrValue<string> | null
    ): AccountUnblockedFromDepositsEventFilter;
    AccountUnblockedFromDeposits(
      accountAddress?: PromiseOrValue<string> | null
    ): AccountUnblockedFromDepositsEventFilter;

    "DisabledForceBuyBacks(address)"(
      market?: null
    ): DisabledForceBuyBacksEventFilter;
    DisabledForceBuyBacks(market?: null): DisabledForceBuyBacksEventFilter;

    "MinimumDepositUpdated(address,uint128)"(
      market?: null,
      newMinimumDeposit?: null
    ): MinimumDepositUpdatedEventFilter;
    MinimumDepositUpdated(
      market?: null,
      newMinimumDeposit?: null
    ): MinimumDepositUpdatedEventFilter;

    "NameUpdated(string)"(name?: null): NameUpdatedEventFilter;
    NameUpdated(name?: null): NameUpdatedEventFilter;

    "RoleProviderAdded(address,uint32,uint24,uint24)"(
      providerAddress?: PromiseOrValue<string> | null,
      timeToLive?: null,
      pullProviderIndex?: null,
      pushProviderIndex?: null
    ): RoleProviderAddedEventFilter;
    RoleProviderAdded(
      providerAddress?: PromiseOrValue<string> | null,
      timeToLive?: null,
      pullProviderIndex?: null,
      pushProviderIndex?: null
    ): RoleProviderAddedEventFilter;

    "RoleProviderRemoved(address,uint24,uint24)"(
      providerAddress?: PromiseOrValue<string> | null,
      pullProviderIndex?: null,
      pushProviderIndex?: null
    ): RoleProviderRemovedEventFilter;
    RoleProviderRemoved(
      providerAddress?: PromiseOrValue<string> | null,
      pullProviderIndex?: null,
      pushProviderIndex?: null
    ): RoleProviderRemovedEventFilter;

    "RoleProviderUpdated(address,uint32,uint24,uint24)"(
      providerAddress?: PromiseOrValue<string> | null,
      timeToLive?: null,
      pullProviderIndex?: null,
      pushProviderIndex?: null
    ): RoleProviderUpdatedEventFilter;
    RoleProviderUpdated(
      providerAddress?: PromiseOrValue<string> | null,
      timeToLive?: null,
      pullProviderIndex?: null,
      pushProviderIndex?: null
    ): RoleProviderUpdatedEventFilter;

    "TemporaryExcessReserveRatioActivated(address,uint256,uint256,uint256)"(
      market?: PromiseOrValue<string> | null,
      originalReserveRatioBips?: null,
      temporaryReserveRatioBips?: null,
      temporaryReserveRatioExpiry?: null
    ): TemporaryExcessReserveRatioActivatedEventFilter;
    TemporaryExcessReserveRatioActivated(
      market?: PromiseOrValue<string> | null,
      originalReserveRatioBips?: null,
      temporaryReserveRatioBips?: null,
      temporaryReserveRatioExpiry?: null
    ): TemporaryExcessReserveRatioActivatedEventFilter;

    "TemporaryExcessReserveRatioCanceled(address)"(
      market?: PromiseOrValue<string> | null
    ): TemporaryExcessReserveRatioCanceledEventFilter;
    TemporaryExcessReserveRatioCanceled(
      market?: PromiseOrValue<string> | null
    ): TemporaryExcessReserveRatioCanceledEventFilter;

    "TemporaryExcessReserveRatioExpired(address)"(
      market?: PromiseOrValue<string> | null
    ): TemporaryExcessReserveRatioExpiredEventFilter;
    TemporaryExcessReserveRatioExpired(
      market?: PromiseOrValue<string> | null
    ): TemporaryExcessReserveRatioExpiredEventFilter;

    "TemporaryExcessReserveRatioUpdated(address,uint256,uint256,uint256)"(
      market?: PromiseOrValue<string> | null,
      originalReserveRatioBips?: null,
      temporaryReserveRatioBips?: null,
      temporaryReserveRatioExpiry?: null
    ): TemporaryExcessReserveRatioUpdatedEventFilter;
    TemporaryExcessReserveRatioUpdated(
      market?: PromiseOrValue<string> | null,
      originalReserveRatioBips?: null,
      temporaryReserveRatioBips?: null,
      temporaryReserveRatioExpiry?: null
    ): TemporaryExcessReserveRatioUpdatedEventFilter;
  };

  estimateGas: {
    addRoleProvider(
      providerAddress: PromiseOrValue<string>,
      timeToLive: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    blockFromDeposits(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    borrower(overrides?: CallOverrides): Promise<BigNumber>;

    config(overrides?: CallOverrides): Promise<BigNumber>;

    createRoleProvider(
      providerFactory: PromiseOrValue<string>,
      timeToLive: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    disableForceBuyBacks(
      market: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    getHookedMarket(
      marketAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getHookedMarkets(
      marketAddresses: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLenderStatus(
      accountAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getParameterConstraints(overrides?: CallOverrides): Promise<BigNumber>;

    getPreviousLenderStatus(
      accountAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPullProviders(overrides?: CallOverrides): Promise<BigNumber>;

    getPushProviders(overrides?: CallOverrides): Promise<BigNumber>;

    getRoleProvider(
      providerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      account: PromiseOrValue<string>,
      roleGrantedTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    grantRoles(
      accounts: PromiseOrValue<string>[],
      roleGrantedTimestamps: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isKnownLenderOnMarket(
      key0: PromiseOrValue<string>,
      key1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    onBorrow(
      param0: PromiseOrValue<BigNumberish>,
      param1: MarketStateV2Struct,
      param2: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    onCloseMarket(
      param0: MarketStateV2Struct,
      param1: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    onCreateMarket(
      deployer: PromiseOrValue<string>,
      marketAddress: PromiseOrValue<string>,
      parameters: DeployMarketInputsV2Struct,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    onDeposit(
      lender: PromiseOrValue<string>,
      scaledAmount: PromiseOrValue<BigNumberish>,
      state: MarketStateV2Struct,
      hooksData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    onExecuteWithdrawal(
      lender: PromiseOrValue<string>,
      param1: PromiseOrValue<BigNumberish>,
      param2: MarketStateV2Struct,
      hooksData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    onForceBuyBack(
      param0: PromiseOrValue<string>,
      param1: PromiseOrValue<BigNumberish>,
      param2: MarketStateV2Struct,
      param3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    onNukeFromOrbit(
      param0: PromiseOrValue<string>,
      param1: MarketStateV2Struct,
      param2: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    onQueueWithdrawal(
      lender: PromiseOrValue<string>,
      param1: PromiseOrValue<BigNumberish>,
      param2: PromiseOrValue<BigNumberish>,
      param3: MarketStateV2Struct,
      hooksData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    onRepay(
      normalizedAmount: PromiseOrValue<BigNumberish>,
      state: MarketStateV2Struct,
      hooksData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    onSetAnnualInterestAndReserveRatioBips(
      annualInterestBips: PromiseOrValue<BigNumberish>,
      reserveRatioBips: PromiseOrValue<BigNumberish>,
      intermediateState: MarketStateV2Struct,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    onSetMaxTotalSupply(
      param0: PromiseOrValue<BigNumberish>,
      param1: MarketStateV2Struct,
      param2: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    onSetProtocolFeeBips(
      param0: PromiseOrValue<BigNumberish>,
      param1: MarketStateV2Struct,
      param2: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    onTransfer(
      param0: PromiseOrValue<string>,
      param1: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      param3: PromiseOrValue<BigNumberish>,
      param4: MarketStateV2Struct,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeRoleProvider(
      providerAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeRole(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMinimumDeposit(
      market: PromiseOrValue<string>,
      newMinimumDeposit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setName(
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    temporaryExcessReserveRatio(
      key0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unblockFromDeposits(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addRoleProvider(
      providerAddress: PromiseOrValue<string>,
      timeToLive: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    blockFromDeposits(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    borrower(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    config(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createRoleProvider(
      providerFactory: PromiseOrValue<string>,
      timeToLive: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    disableForceBuyBacks(
      market: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getHookedMarket(
      marketAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getHookedMarkets(
      marketAddresses: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLenderStatus(
      accountAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getParameterConstraints(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPreviousLenderStatus(
      accountAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPullProviders(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPushProviders(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRoleProvider(
      providerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      account: PromiseOrValue<string>,
      roleGrantedTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    grantRoles(
      accounts: PromiseOrValue<string>[],
      roleGrantedTimestamps: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isKnownLenderOnMarket(
      key0: PromiseOrValue<string>,
      key1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onBorrow(
      param0: PromiseOrValue<BigNumberish>,
      param1: MarketStateV2Struct,
      param2: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    onCloseMarket(
      param0: MarketStateV2Struct,
      param1: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    onCreateMarket(
      deployer: PromiseOrValue<string>,
      marketAddress: PromiseOrValue<string>,
      parameters: DeployMarketInputsV2Struct,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    onDeposit(
      lender: PromiseOrValue<string>,
      scaledAmount: PromiseOrValue<BigNumberish>,
      state: MarketStateV2Struct,
      hooksData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    onExecuteWithdrawal(
      lender: PromiseOrValue<string>,
      param1: PromiseOrValue<BigNumberish>,
      param2: MarketStateV2Struct,
      hooksData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    onForceBuyBack(
      param0: PromiseOrValue<string>,
      param1: PromiseOrValue<BigNumberish>,
      param2: MarketStateV2Struct,
      param3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    onNukeFromOrbit(
      param0: PromiseOrValue<string>,
      param1: MarketStateV2Struct,
      param2: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    onQueueWithdrawal(
      lender: PromiseOrValue<string>,
      param1: PromiseOrValue<BigNumberish>,
      param2: PromiseOrValue<BigNumberish>,
      param3: MarketStateV2Struct,
      hooksData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    onRepay(
      normalizedAmount: PromiseOrValue<BigNumberish>,
      state: MarketStateV2Struct,
      hooksData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    onSetAnnualInterestAndReserveRatioBips(
      annualInterestBips: PromiseOrValue<BigNumberish>,
      reserveRatioBips: PromiseOrValue<BigNumberish>,
      intermediateState: MarketStateV2Struct,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    onSetMaxTotalSupply(
      param0: PromiseOrValue<BigNumberish>,
      param1: MarketStateV2Struct,
      param2: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    onSetProtocolFeeBips(
      param0: PromiseOrValue<BigNumberish>,
      param1: MarketStateV2Struct,
      param2: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    onTransfer(
      param0: PromiseOrValue<string>,
      param1: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      param3: PromiseOrValue<BigNumberish>,
      param4: MarketStateV2Struct,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeRoleProvider(
      providerAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMinimumDeposit(
      market: PromiseOrValue<string>,
      newMinimumDeposit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setName(
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    temporaryExcessReserveRatio(
      key0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unblockFromDeposits(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
