/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type PeriodicTermHookedMarketStruct = {
  isHooked: PromiseOrValue<boolean>;
  transferRequiresAccess: PromiseOrValue<boolean>;
  depositRequiresAccess: PromiseOrValue<boolean>;
  withdrawalRequiresAccess: PromiseOrValue<boolean>;
  depositHookEnabled: PromiseOrValue<boolean>;
  minimumDeposit: PromiseOrValue<BigNumberish>;
  firstWithdrawalWindowStart: PromiseOrValue<BigNumberish>;
  periodDuration: PromiseOrValue<BigNumberish>;
  withdrawalWindowDuration: PromiseOrValue<BigNumberish>;
  transfersDisabled: PromiseOrValue<boolean>;
  isClosed: PromiseOrValue<boolean>;
};

export type PeriodicTermHookedMarketStructOutput = {
  isHooked: boolean;
  transferRequiresAccess: boolean;
  depositRequiresAccess: boolean;
  withdrawalRequiresAccess: boolean;
  depositHookEnabled: boolean;
  minimumDeposit: BigNumber;
  firstWithdrawalWindowStart: number;
  periodDuration: number;
  withdrawalWindowDuration: number;
  transfersDisabled: boolean;
  isClosed: boolean;
};

export type LenderStatusStruct = {
  isBlockedFromDeposits: PromiseOrValue<boolean>;
  lastProvider: PromiseOrValue<string>;
  canRefresh: PromiseOrValue<boolean>;
  lastApprovalTimestamp: PromiseOrValue<BigNumberish>;
};

export type LenderStatusStructOutput = {
  isBlockedFromDeposits: boolean;
  lastProvider: string;
  canRefresh: boolean;
  lastApprovalTimestamp: number;
};

export type MarketParameterConstraintsStruct = {
  minimumDelinquencyGracePeriod: PromiseOrValue<BigNumberish>;
  maximumDelinquencyGracePeriod: PromiseOrValue<BigNumberish>;
  minimumReserveRatioBips: PromiseOrValue<BigNumberish>;
  maximumReserveRatioBips: PromiseOrValue<BigNumberish>;
  minimumDelinquencyFeeBips: PromiseOrValue<BigNumberish>;
  maximumDelinquencyFeeBips: PromiseOrValue<BigNumberish>;
  minimumWithdrawalBatchDuration: PromiseOrValue<BigNumberish>;
  maximumWithdrawalBatchDuration: PromiseOrValue<BigNumberish>;
  minimumAnnualInterestBips: PromiseOrValue<BigNumberish>;
  maximumAnnualInterestBips: PromiseOrValue<BigNumberish>;
};

export type MarketParameterConstraintsStructOutput = {
  minimumDelinquencyGracePeriod: number;
  maximumDelinquencyGracePeriod: number;
  minimumReserveRatioBips: number;
  maximumReserveRatioBips: number;
  minimumDelinquencyFeeBips: number;
  maximumDelinquencyFeeBips: number;
  minimumWithdrawalBatchDuration: number;
  maximumWithdrawalBatchDuration: number;
  minimumAnnualInterestBips: number;
  maximumAnnualInterestBips: number;
};

export type PendingAprChangeStruct = {
  annualInterestBips: PromiseOrValue<BigNumberish>;
  proposalTimestamp: PromiseOrValue<BigNumberish>;
};

export type PendingAprChangeStructOutput = {
  annualInterestBips: number;
  proposalTimestamp: number;
};

export interface IPeriodicTermHooksInterface extends utils.Interface {
  functions: {
    "addRoleProvider(address,uint32)": FunctionFragment;
    "blockFromDeposits(address)": FunctionFragment;
    "blockFromDeposits(address[])": FunctionFragment;
    "borrower()": FunctionFragment;
    "config()": FunctionFragment;
    "getHookedMarket(address)": FunctionFragment;
    "getHookedMarkets(address[])": FunctionFragment;
    "getLenderStatus(address)": FunctionFragment;
    "getParameterConstraints()": FunctionFragment;
    "getPendingAprChange(address)": FunctionFragment;
    "getPreviousLenderStatus(address)": FunctionFragment;
    "getPullProviders()": FunctionFragment;
    "getPushProviders()": FunctionFragment;
    "getRoleProvider(address)": FunctionFragment;
    "grantRole(address,uint32)": FunctionFragment;
    "grantRoles(address[],uint32[])": FunctionFragment;
    "isKnownLenderOnMarket(address,address)": FunctionFragment;
    "isWithdrawalWindowOpen(address)": FunctionFragment;
    "name()": FunctionFragment;
    "pendingAprChanges(address)": FunctionFragment;
    "proposeAnnualInterestBips(address,uint16)": FunctionFragment;
    "removeRoleProvider(address)": FunctionFragment;
    "revokeRole(address)": FunctionFragment;
    "setMinimumDeposit(address,uint128)": FunctionFragment;
    "setName(string)": FunctionFragment;
    "unblockFromDeposits(address)": FunctionFragment;
    "version()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addRoleProvider"
      | "blockFromDeposits(address)"
      | "blockFromDeposits(address[])"
      | "borrower"
      | "config"
      | "getHookedMarket"
      | "getHookedMarkets"
      | "getLenderStatus"
      | "getParameterConstraints"
      | "getPendingAprChange"
      | "getPreviousLenderStatus"
      | "getPullProviders"
      | "getPushProviders"
      | "getRoleProvider"
      | "grantRole"
      | "grantRoles"
      | "isKnownLenderOnMarket"
      | "isWithdrawalWindowOpen"
      | "name"
      | "pendingAprChanges"
      | "proposeAnnualInterestBips"
      | "removeRoleProvider"
      | "revokeRole"
      | "setMinimumDeposit"
      | "setName"
      | "unblockFromDeposits"
      | "version"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addRoleProvider",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "blockFromDeposits(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "blockFromDeposits(address[])",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(functionFragment: "borrower", values?: undefined): string;
  encodeFunctionData(functionFragment: "config", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getHookedMarket",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getHookedMarkets",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getLenderStatus",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getParameterConstraints",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingAprChange",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPreviousLenderStatus",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPullProviders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPushProviders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleProvider",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRoles",
    values: [PromiseOrValue<string>[], PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isKnownLenderOnMarket",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isWithdrawalWindowOpen",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingAprChanges",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeAnnualInterestBips",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeRoleProvider",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinimumDeposit",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setName",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "unblockFromDeposits",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "addRoleProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blockFromDeposits(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blockFromDeposits(address[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "borrower", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "config", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getHookedMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHookedMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLenderStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParameterConstraints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingAprChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPreviousLenderStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPullProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPushProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grantRoles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isKnownLenderOnMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWithdrawalWindowOpen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingAprChanges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeAnnualInterestBips",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeRoleProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMinimumDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unblockFromDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;

  events: {
    "AccountAccessGranted(address,address,uint32)": EventFragment;
    "AccountAccessRevoked(address)": EventFragment;
    "AccountBlockedFromDeposits(address)": EventFragment;
    "AccountMadeFirstDeposit(address,address)": EventFragment;
    "AccountUnblockedFromDeposits(address)": EventFragment;
    "AnnualInterestBipsReductionProposed(address,uint16,uint32,uint32,uint32)": EventFragment;
    "MinimumDepositUpdated(address,uint128)": EventFragment;
    "NameUpdated(string)": EventFragment;
    "PeriodicTermClosed(address)": EventFragment;
    "PeriodicTermUpdated(address,uint32,uint32,uint32)": EventFragment;
    "RoleProviderAdded(address,uint32,uint24,uint24)": EventFragment;
    "RoleProviderRemoved(address,uint24,uint24)": EventFragment;
    "RoleProviderUpdated(address,uint32,uint24,uint24)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AccountAccessGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AccountAccessRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AccountBlockedFromDeposits"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AccountMadeFirstDeposit"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "AccountUnblockedFromDeposits"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "AnnualInterestBipsReductionProposed"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MinimumDepositUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NameUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PeriodicTermClosed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PeriodicTermUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleProviderAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleProviderRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleProviderUpdated"): EventFragment;
}

export interface AccountAccessGrantedEventObject {
  providerAddress: string;
  accountAddress: string;
  credentialTimestamp: number;
}
export type AccountAccessGrantedEvent = TypedEvent<
  [string, string, number],
  AccountAccessGrantedEventObject
>;

export type AccountAccessGrantedEventFilter =
  TypedEventFilter<AccountAccessGrantedEvent>;

export interface AccountAccessRevokedEventObject {
  accountAddress: string;
}
export type AccountAccessRevokedEvent = TypedEvent<
  [string],
  AccountAccessRevokedEventObject
>;

export type AccountAccessRevokedEventFilter =
  TypedEventFilter<AccountAccessRevokedEvent>;

export interface AccountBlockedFromDepositsEventObject {
  accountAddress: string;
}
export type AccountBlockedFromDepositsEvent = TypedEvent<
  [string],
  AccountBlockedFromDepositsEventObject
>;

export type AccountBlockedFromDepositsEventFilter =
  TypedEventFilter<AccountBlockedFromDepositsEvent>;

export interface AccountMadeFirstDepositEventObject {
  market: string;
  accountAddress: string;
}
export type AccountMadeFirstDepositEvent = TypedEvent<
  [string, string],
  AccountMadeFirstDepositEventObject
>;

export type AccountMadeFirstDepositEventFilter =
  TypedEventFilter<AccountMadeFirstDepositEvent>;

export interface AccountUnblockedFromDepositsEventObject {
  accountAddress: string;
}
export type AccountUnblockedFromDepositsEvent = TypedEvent<
  [string],
  AccountUnblockedFromDepositsEventObject
>;

export type AccountUnblockedFromDepositsEventFilter =
  TypedEventFilter<AccountUnblockedFromDepositsEvent>;

export interface AnnualInterestBipsReductionProposedEventObject {
  market: string;
  annualInterestBips: number;
  proposalTimestamp: number;
  responseWindowStart: number;
  responseWindowEnd: number;
}
export type AnnualInterestBipsReductionProposedEvent = TypedEvent<
  [string, number, number, number, number],
  AnnualInterestBipsReductionProposedEventObject
>;

export type AnnualInterestBipsReductionProposedEventFilter =
  TypedEventFilter<AnnualInterestBipsReductionProposedEvent>;

export interface MinimumDepositUpdatedEventObject {
  market: string;
  newMinimumDeposit: BigNumber;
}
export type MinimumDepositUpdatedEvent = TypedEvent<
  [string, BigNumber],
  MinimumDepositUpdatedEventObject
>;

export type MinimumDepositUpdatedEventFilter =
  TypedEventFilter<MinimumDepositUpdatedEvent>;

export interface NameUpdatedEventObject {
  name: string;
}
export type NameUpdatedEvent = TypedEvent<[string], NameUpdatedEventObject>;

export type NameUpdatedEventFilter = TypedEventFilter<NameUpdatedEvent>;

export interface PeriodicTermClosedEventObject {
  market: string;
}
export type PeriodicTermClosedEvent = TypedEvent<
  [string],
  PeriodicTermClosedEventObject
>;

export type PeriodicTermClosedEventFilter =
  TypedEventFilter<PeriodicTermClosedEvent>;

export interface PeriodicTermUpdatedEventObject {
  market: string;
  firstWithdrawalWindowStart: number;
  periodDuration: number;
  withdrawalWindowDuration: number;
}
export type PeriodicTermUpdatedEvent = TypedEvent<
  [string, number, number, number],
  PeriodicTermUpdatedEventObject
>;

export type PeriodicTermUpdatedEventFilter =
  TypedEventFilter<PeriodicTermUpdatedEvent>;

export interface RoleProviderAddedEventObject {
  providerAddress: string;
  timeToLive: number;
  pullProviderIndex: number;
  pushProviderIndex: number;
}
export type RoleProviderAddedEvent = TypedEvent<
  [string, number, number, number],
  RoleProviderAddedEventObject
>;

export type RoleProviderAddedEventFilter =
  TypedEventFilter<RoleProviderAddedEvent>;

export interface RoleProviderRemovedEventObject {
  providerAddress: string;
  pullProviderIndex: number;
  pushProviderIndex: number;
}
export type RoleProviderRemovedEvent = TypedEvent<
  [string, number, number],
  RoleProviderRemovedEventObject
>;

export type RoleProviderRemovedEventFilter =
  TypedEventFilter<RoleProviderRemovedEvent>;

export interface RoleProviderUpdatedEventObject {
  providerAddress: string;
  timeToLive: number;
  pullProviderIndex: number;
  pushProviderIndex: number;
}
export type RoleProviderUpdatedEvent = TypedEvent<
  [string, number, number, number],
  RoleProviderUpdatedEventObject
>;

export type RoleProviderUpdatedEventFilter =
  TypedEventFilter<RoleProviderUpdatedEvent>;

export interface IPeriodicTermHooks extends BaseContract {
  contractName: "IPeriodicTermHooks";

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPeriodicTermHooksInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addRoleProvider(
      providerAddress: PromiseOrValue<string>,
      timeToLive: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "blockFromDeposits(address)"(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "blockFromDeposits(address[])"(
      accounts: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    borrower(overrides?: CallOverrides): Promise<[string]>;

    config(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { param0: BigNumber }>;

    getHookedMarket(
      marketAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [PeriodicTermHookedMarketStructOutput] & {
        param0: PeriodicTermHookedMarketStructOutput;
      }
    >;

    getHookedMarkets(
      marketAddresses: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<
      [PeriodicTermHookedMarketStructOutput[]] & {
        hookedMarkets: PeriodicTermHookedMarketStructOutput[];
      }
    >;

    getLenderStatus(
      accountAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [LenderStatusStructOutput] & { status: LenderStatusStructOutput }
    >;

    getParameterConstraints(
      overrides?: CallOverrides
    ): Promise<
      [MarketParameterConstraintsStructOutput] & {
        constraints: MarketParameterConstraintsStructOutput;
      }
    >;

    getPendingAprChange(
      marketAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [PendingAprChangeStructOutput, number, number] & {
        pendingAprChange: PendingAprChangeStructOutput;
        responseWindowStart: number;
        responseWindowEnd: number;
      }
    >;

    getPreviousLenderStatus(
      accountAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [LenderStatusStructOutput] & { status: LenderStatusStructOutput }
    >;

    getPullProviders(
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { param0: BigNumber[] }>;

    getPushProviders(
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { param0: BigNumber[] }>;

    getRoleProvider(
      providerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { param0: BigNumber }>;

    grantRole(
      account: PromiseOrValue<string>,
      roleGrantedTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    grantRoles(
      accounts: PromiseOrValue<string>[],
      roleGrantedTimestamps: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isKnownLenderOnMarket(
      key0: PromiseOrValue<string>,
      key1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isWithdrawalWindowOpen(
      marketAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    pendingAprChanges(
      market: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [number, number] & {
        annualInterestBips: number;
        proposalTimestamp: number;
      }
    >;

    proposeAnnualInterestBips(
      market: PromiseOrValue<string>,
      annualInterestBips: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeRoleProvider(
      providerAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMinimumDeposit(
      market: PromiseOrValue<string>,
      newMinimumDeposit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setName(
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unblockFromDeposits(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    version(overrides?: CallOverrides): Promise<[string] & { param0: string }>;
  };

  addRoleProvider(
    providerAddress: PromiseOrValue<string>,
    timeToLive: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "blockFromDeposits(address)"(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "blockFromDeposits(address[])"(
    accounts: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  borrower(overrides?: CallOverrides): Promise<string>;

  config(overrides?: CallOverrides): Promise<BigNumber>;

  getHookedMarket(
    marketAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<PeriodicTermHookedMarketStructOutput>;

  getHookedMarkets(
    marketAddresses: PromiseOrValue<string>[],
    overrides?: CallOverrides
  ): Promise<PeriodicTermHookedMarketStructOutput[]>;

  getLenderStatus(
    accountAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<LenderStatusStructOutput>;

  getParameterConstraints(
    overrides?: CallOverrides
  ): Promise<MarketParameterConstraintsStructOutput>;

  getPendingAprChange(
    marketAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [PendingAprChangeStructOutput, number, number] & {
      pendingAprChange: PendingAprChangeStructOutput;
      responseWindowStart: number;
      responseWindowEnd: number;
    }
  >;

  getPreviousLenderStatus(
    accountAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<LenderStatusStructOutput>;

  getPullProviders(overrides?: CallOverrides): Promise<BigNumber[]>;

  getPushProviders(overrides?: CallOverrides): Promise<BigNumber[]>;

  getRoleProvider(
    providerAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  grantRole(
    account: PromiseOrValue<string>,
    roleGrantedTimestamp: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  grantRoles(
    accounts: PromiseOrValue<string>[],
    roleGrantedTimestamps: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isKnownLenderOnMarket(
    key0: PromiseOrValue<string>,
    key1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isWithdrawalWindowOpen(
    marketAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  name(overrides?: CallOverrides): Promise<string>;

  pendingAprChanges(
    market: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [number, number] & { annualInterestBips: number; proposalTimestamp: number }
  >;

  proposeAnnualInterestBips(
    market: PromiseOrValue<string>,
    annualInterestBips: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeRoleProvider(
    providerAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMinimumDeposit(
    market: PromiseOrValue<string>,
    newMinimumDeposit: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setName(
    _name: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unblockFromDeposits(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  version(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    addRoleProvider(
      providerAddress: PromiseOrValue<string>,
      timeToLive: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "blockFromDeposits(address)"(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    "blockFromDeposits(address[])"(
      accounts: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    borrower(overrides?: CallOverrides): Promise<string>;

    config(overrides?: CallOverrides): Promise<BigNumber>;

    getHookedMarket(
      marketAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PeriodicTermHookedMarketStructOutput>;

    getHookedMarkets(
      marketAddresses: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<PeriodicTermHookedMarketStructOutput[]>;

    getLenderStatus(
      accountAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<LenderStatusStructOutput>;

    getParameterConstraints(
      overrides?: CallOverrides
    ): Promise<MarketParameterConstraintsStructOutput>;

    getPendingAprChange(
      marketAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [PendingAprChangeStructOutput, number, number] & {
        pendingAprChange: PendingAprChangeStructOutput;
        responseWindowStart: number;
        responseWindowEnd: number;
      }
    >;

    getPreviousLenderStatus(
      accountAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<LenderStatusStructOutput>;

    getPullProviders(overrides?: CallOverrides): Promise<BigNumber[]>;

    getPushProviders(overrides?: CallOverrides): Promise<BigNumber[]>;

    getRoleProvider(
      providerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      account: PromiseOrValue<string>,
      roleGrantedTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    grantRoles(
      accounts: PromiseOrValue<string>[],
      roleGrantedTimestamps: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    isKnownLenderOnMarket(
      key0: PromiseOrValue<string>,
      key1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isWithdrawalWindowOpen(
      marketAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    name(overrides?: CallOverrides): Promise<string>;

    pendingAprChanges(
      market: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [number, number] & {
        annualInterestBips: number;
        proposalTimestamp: number;
      }
    >;

    proposeAnnualInterestBips(
      market: PromiseOrValue<string>,
      annualInterestBips: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeRoleProvider(
      providerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMinimumDeposit(
      market: PromiseOrValue<string>,
      newMinimumDeposit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setName(
      _name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unblockFromDeposits(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    version(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "AccountAccessGranted(address,address,uint32)"(
      providerAddress?: PromiseOrValue<string> | null,
      accountAddress?: PromiseOrValue<string> | null,
      credentialTimestamp?: null
    ): AccountAccessGrantedEventFilter;
    AccountAccessGranted(
      providerAddress?: PromiseOrValue<string> | null,
      accountAddress?: PromiseOrValue<string> | null,
      credentialTimestamp?: null
    ): AccountAccessGrantedEventFilter;

    "AccountAccessRevoked(address)"(
      accountAddress?: PromiseOrValue<string> | null
    ): AccountAccessRevokedEventFilter;
    AccountAccessRevoked(
      accountAddress?: PromiseOrValue<string> | null
    ): AccountAccessRevokedEventFilter;

    "AccountBlockedFromDeposits(address)"(
      accountAddress?: PromiseOrValue<string> | null
    ): AccountBlockedFromDepositsEventFilter;
    AccountBlockedFromDeposits(
      accountAddress?: PromiseOrValue<string> | null
    ): AccountBlockedFromDepositsEventFilter;

    "AccountMadeFirstDeposit(address,address)"(
      market?: PromiseOrValue<string> | null,
      accountAddress?: PromiseOrValue<string> | null
    ): AccountMadeFirstDepositEventFilter;
    AccountMadeFirstDeposit(
      market?: PromiseOrValue<string> | null,
      accountAddress?: PromiseOrValue<string> | null
    ): AccountMadeFirstDepositEventFilter;

    "AccountUnblockedFromDeposits(address)"(
      accountAddress?: PromiseOrValue<string> | null
    ): AccountUnblockedFromDepositsEventFilter;
    AccountUnblockedFromDeposits(
      accountAddress?: PromiseOrValue<string> | null
    ): AccountUnblockedFromDepositsEventFilter;

    "AnnualInterestBipsReductionProposed(address,uint16,uint32,uint32,uint32)"(
      market?: PromiseOrValue<string> | null,
      annualInterestBips?: null,
      proposalTimestamp?: null,
      responseWindowStart?: null,
      responseWindowEnd?: null
    ): AnnualInterestBipsReductionProposedEventFilter;
    AnnualInterestBipsReductionProposed(
      market?: PromiseOrValue<string> | null,
      annualInterestBips?: null,
      proposalTimestamp?: null,
      responseWindowStart?: null,
      responseWindowEnd?: null
    ): AnnualInterestBipsReductionProposedEventFilter;

    "MinimumDepositUpdated(address,uint128)"(
      market?: null,
      newMinimumDeposit?: null
    ): MinimumDepositUpdatedEventFilter;
    MinimumDepositUpdated(
      market?: null,
      newMinimumDeposit?: null
    ): MinimumDepositUpdatedEventFilter;

    "NameUpdated(string)"(name?: null): NameUpdatedEventFilter;
    NameUpdated(name?: null): NameUpdatedEventFilter;

    "PeriodicTermClosed(address)"(market?: null): PeriodicTermClosedEventFilter;
    PeriodicTermClosed(market?: null): PeriodicTermClosedEventFilter;

    "PeriodicTermUpdated(address,uint32,uint32,uint32)"(
      market?: null,
      firstWithdrawalWindowStart?: null,
      periodDuration?: null,
      withdrawalWindowDuration?: null
    ): PeriodicTermUpdatedEventFilter;
    PeriodicTermUpdated(
      market?: null,
      firstWithdrawalWindowStart?: null,
      periodDuration?: null,
      withdrawalWindowDuration?: null
    ): PeriodicTermUpdatedEventFilter;

    "RoleProviderAdded(address,uint32,uint24,uint24)"(
      providerAddress?: PromiseOrValue<string> | null,
      timeToLive?: null,
      pullProviderIndex?: null,
      pushProviderIndex?: null
    ): RoleProviderAddedEventFilter;
    RoleProviderAdded(
      providerAddress?: PromiseOrValue<string> | null,
      timeToLive?: null,
      pullProviderIndex?: null,
      pushProviderIndex?: null
    ): RoleProviderAddedEventFilter;

    "RoleProviderRemoved(address,uint24,uint24)"(
      providerAddress?: PromiseOrValue<string> | null,
      pullProviderIndex?: null,
      pushProviderIndex?: null
    ): RoleProviderRemovedEventFilter;
    RoleProviderRemoved(
      providerAddress?: PromiseOrValue<string> | null,
      pullProviderIndex?: null,
      pushProviderIndex?: null
    ): RoleProviderRemovedEventFilter;

    "RoleProviderUpdated(address,uint32,uint24,uint24)"(
      providerAddress?: PromiseOrValue<string> | null,
      timeToLive?: null,
      pullProviderIndex?: null,
      pushProviderIndex?: null
    ): RoleProviderUpdatedEventFilter;
    RoleProviderUpdated(
      providerAddress?: PromiseOrValue<string> | null,
      timeToLive?: null,
      pullProviderIndex?: null,
      pushProviderIndex?: null
    ): RoleProviderUpdatedEventFilter;
  };

  estimateGas: {
    addRoleProvider(
      providerAddress: PromiseOrValue<string>,
      timeToLive: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "blockFromDeposits(address)"(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "blockFromDeposits(address[])"(
      accounts: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    borrower(overrides?: CallOverrides): Promise<BigNumber>;

    config(overrides?: CallOverrides): Promise<BigNumber>;

    getHookedMarket(
      marketAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getHookedMarkets(
      marketAddresses: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLenderStatus(
      accountAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getParameterConstraints(overrides?: CallOverrides): Promise<BigNumber>;

    getPendingAprChange(
      marketAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPreviousLenderStatus(
      accountAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPullProviders(overrides?: CallOverrides): Promise<BigNumber>;

    getPushProviders(overrides?: CallOverrides): Promise<BigNumber>;

    getRoleProvider(
      providerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      account: PromiseOrValue<string>,
      roleGrantedTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    grantRoles(
      accounts: PromiseOrValue<string>[],
      roleGrantedTimestamps: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isKnownLenderOnMarket(
      key0: PromiseOrValue<string>,
      key1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isWithdrawalWindowOpen(
      marketAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    pendingAprChanges(
      market: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proposeAnnualInterestBips(
      market: PromiseOrValue<string>,
      annualInterestBips: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeRoleProvider(
      providerAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeRole(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMinimumDeposit(
      market: PromiseOrValue<string>,
      newMinimumDeposit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setName(
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unblockFromDeposits(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addRoleProvider(
      providerAddress: PromiseOrValue<string>,
      timeToLive: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "blockFromDeposits(address)"(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "blockFromDeposits(address[])"(
      accounts: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    borrower(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    config(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getHookedMarket(
      marketAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getHookedMarkets(
      marketAddresses: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLenderStatus(
      accountAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getParameterConstraints(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPendingAprChange(
      marketAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPreviousLenderStatus(
      accountAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPullProviders(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPushProviders(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRoleProvider(
      providerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      account: PromiseOrValue<string>,
      roleGrantedTimestamp: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    grantRoles(
      accounts: PromiseOrValue<string>[],
      roleGrantedTimestamps: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isKnownLenderOnMarket(
      key0: PromiseOrValue<string>,
      key1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isWithdrawalWindowOpen(
      marketAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingAprChanges(
      market: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proposeAnnualInterestBips(
      market: PromiseOrValue<string>,
      annualInterestBips: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeRoleProvider(
      providerAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMinimumDeposit(
      market: PromiseOrValue<string>,
      newMinimumDeposit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setName(
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unblockFromDeposits(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
