/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type TokenMetadataStruct = {
  token: PromiseOrValue<string>;
  name: PromiseOrValue<string>;
  symbol: PromiseOrValue<string>;
  decimals: PromiseOrValue<BigNumberish>;
  isMock: PromiseOrValue<boolean>;
};

export type TokenMetadataStructOutput = {
  token: string;
  name: string;
  symbol: string;
  decimals: BigNumber;
  isMock: boolean;
};

export type FeeConfigurationV21Struct = {
  feeRecipient: PromiseOrValue<string>;
  protocolFeeBips: PromiseOrValue<BigNumberish>;
  originationFeeToken: TokenMetadataStruct;
  originationFeeAmount: PromiseOrValue<BigNumberish>;
  borrowerOriginationFeeBalance: PromiseOrValue<BigNumberish>;
  borrowerOriginationFeeApproval: PromiseOrValue<BigNumberish>;
};

export type FeeConfigurationV21StructOutput = {
  feeRecipient: string;
  protocolFeeBips: number;
  originationFeeToken: TokenMetadataStructOutput;
  originationFeeAmount: BigNumber;
  borrowerOriginationFeeBalance: BigNumber;
  borrowerOriginationFeeApproval: BigNumber;
};

export type HooksTemplateDataV21Struct = {
  hooksTemplate: PromiseOrValue<string>;
  fees: FeeConfigurationV21Struct;
  exists: PromiseOrValue<boolean>;
  enabled: PromiseOrValue<boolean>;
  index: PromiseOrValue<BigNumberish>;
  name: PromiseOrValue<string>;
  totalMarkets: PromiseOrValue<BigNumberish>;
};

export type HooksTemplateDataV21StructOutput = {
  hooksTemplate: string;
  fees: FeeConfigurationV21StructOutput;
  exists: boolean;
  enabled: boolean;
  index: number;
  name: string;
  totalMarkets: BigNumber;
};

export type HooksConfigDataV21Struct = {
  useOnDeposit: PromiseOrValue<boolean>;
  useOnQueueWithdrawal: PromiseOrValue<boolean>;
  useOnExecuteWithdrawal: PromiseOrValue<boolean>;
  useOnTransfer: PromiseOrValue<boolean>;
  useOnBorrow: PromiseOrValue<boolean>;
  useOnRepay: PromiseOrValue<boolean>;
  useOnCloseMarket: PromiseOrValue<boolean>;
  useOnNukeFromOrbit: PromiseOrValue<boolean>;
  useOnSetMaxTotalSupply: PromiseOrValue<boolean>;
  useOnSetAnnualInterestAndReserveRatioBips: PromiseOrValue<boolean>;
  useOnSetProtocolFeeBips: PromiseOrValue<boolean>;
};

export type HooksConfigDataV21StructOutput = {
  useOnDeposit: boolean;
  useOnQueueWithdrawal: boolean;
  useOnExecuteWithdrawal: boolean;
  useOnTransfer: boolean;
  useOnBorrow: boolean;
  useOnRepay: boolean;
  useOnCloseMarket: boolean;
  useOnNukeFromOrbit: boolean;
  useOnSetMaxTotalSupply: boolean;
  useOnSetAnnualInterestAndReserveRatioBips: boolean;
  useOnSetProtocolFeeBips: boolean;
};

export type MarketHooksDataV21Struct = {
  hooksAddress: PromiseOrValue<string>;
  flags: HooksConfigDataV21Struct;
  kind: PromiseOrValue<BigNumberish>;
  transferRequiresAccess: PromiseOrValue<boolean>;
  depositRequiresAccess: PromiseOrValue<boolean>;
  minimumDeposit: PromiseOrValue<BigNumberish>;
  transfersDisabled: PromiseOrValue<boolean>;
  withdrawalRequiresAccess: PromiseOrValue<boolean>;
  fixedTermEndTime: PromiseOrValue<BigNumberish>;
  allowClosureBeforeTerm: PromiseOrValue<boolean>;
  allowTermReduction: PromiseOrValue<boolean>;
  firstWithdrawalWindowStart: PromiseOrValue<BigNumberish>;
  periodDuration: PromiseOrValue<BigNumberish>;
  withdrawalWindowDuration: PromiseOrValue<BigNumberish>;
  periodicTermClosed: PromiseOrValue<boolean>;
};

export type MarketHooksDataV21StructOutput = {
  hooksAddress: string;
  flags: HooksConfigDataV21StructOutput;
  kind: number;
  transferRequiresAccess: boolean;
  depositRequiresAccess: boolean;
  minimumDeposit: BigNumber;
  transfersDisabled: boolean;
  withdrawalRequiresAccess: boolean;
  fixedTermEndTime: number;
  allowClosureBeforeTerm: boolean;
  allowTermReduction: boolean;
  firstWithdrawalWindowStart: number;
  periodDuration: number;
  withdrawalWindowDuration: number;
  periodicTermClosed: boolean;
};

export type MarketParameterConstraintsStruct = {
  minimumDelinquencyGracePeriod: PromiseOrValue<BigNumberish>;
  maximumDelinquencyGracePeriod: PromiseOrValue<BigNumberish>;
  minimumReserveRatioBips: PromiseOrValue<BigNumberish>;
  maximumReserveRatioBips: PromiseOrValue<BigNumberish>;
  minimumDelinquencyFeeBips: PromiseOrValue<BigNumberish>;
  maximumDelinquencyFeeBips: PromiseOrValue<BigNumberish>;
  minimumWithdrawalBatchDuration: PromiseOrValue<BigNumberish>;
  maximumWithdrawalBatchDuration: PromiseOrValue<BigNumberish>;
  minimumAnnualInterestBips: PromiseOrValue<BigNumberish>;
  maximumAnnualInterestBips: PromiseOrValue<BigNumberish>;
};

export type MarketParameterConstraintsStructOutput = {
  minimumDelinquencyGracePeriod: number;
  maximumDelinquencyGracePeriod: number;
  minimumReserveRatioBips: number;
  maximumReserveRatioBips: number;
  minimumDelinquencyFeeBips: number;
  maximumDelinquencyFeeBips: number;
  minimumWithdrawalBatchDuration: number;
  maximumWithdrawalBatchDuration: number;
  minimumAnnualInterestBips: number;
  maximumAnnualInterestBips: number;
};

export type HooksDeploymentFlagsV21Struct = {
  optional: HooksConfigDataV21Struct;
  required: HooksConfigDataV21Struct;
};

export type HooksDeploymentFlagsV21StructOutput = {
  optional: HooksConfigDataV21StructOutput;
  required: HooksConfigDataV21StructOutput;
};

export type RoleProviderDataV21Struct = {
  timeToLive: PromiseOrValue<BigNumberish>;
  providerAddress: PromiseOrValue<string>;
  pullProviderIndex: PromiseOrValue<BigNumberish>;
  pushProviderIndex: PromiseOrValue<BigNumberish>;
};

export type RoleProviderDataV21StructOutput = {
  timeToLive: number;
  providerAddress: string;
  pullProviderIndex: number;
  pushProviderIndex: number;
};

export type HooksInstanceDataV21Struct = {
  hooksAddress: PromiseOrValue<string>;
  borrower: PromiseOrValue<string>;
  name: PromiseOrValue<string>;
  kind: PromiseOrValue<BigNumberish>;
  hooksTemplate: HooksTemplateDataV21Struct;
  constraints: MarketParameterConstraintsStruct;
  deploymentFlags: HooksDeploymentFlagsV21Struct;
  pullProviders: RoleProviderDataV21Struct[];
  pushProviders: RoleProviderDataV21Struct[];
  totalMarkets: PromiseOrValue<BigNumberish>;
};

export type HooksInstanceDataV21StructOutput = {
  hooksAddress: string;
  borrower: string;
  name: string;
  kind: number;
  hooksTemplate: HooksTemplateDataV21StructOutput;
  constraints: MarketParameterConstraintsStructOutput;
  deploymentFlags: HooksDeploymentFlagsV21StructOutput;
  pullProviders: RoleProviderDataV21StructOutput[];
  pushProviders: RoleProviderDataV21StructOutput[];
  totalMarkets: BigNumber;
};

export type MarketDataV21Struct = {
  marketToken: TokenMetadataStruct;
  underlyingToken: TokenMetadataStruct;
  hooksFactory: PromiseOrValue<string>;
  borrower: PromiseOrValue<string>;
  hooksConfig: MarketHooksDataV21Struct;
  withdrawalBatchDuration: PromiseOrValue<BigNumberish>;
  feeRecipient: PromiseOrValue<string>;
  delinquencyFeeBips: PromiseOrValue<BigNumberish>;
  delinquencyGracePeriod: PromiseOrValue<BigNumberish>;
  hooks: HooksInstanceDataV21Struct;
  temporaryReserveRatio: PromiseOrValue<boolean>;
  originalAnnualInterestBips: PromiseOrValue<BigNumberish>;
  originalReserveRatioBips: PromiseOrValue<BigNumberish>;
  temporaryReserveRatioExpiry: PromiseOrValue<BigNumberish>;
  isClosed: PromiseOrValue<boolean>;
  protocolFeeBips: PromiseOrValue<BigNumberish>;
  reserveRatioBips: PromiseOrValue<BigNumberish>;
  annualInterestBips: PromiseOrValue<BigNumberish>;
  scaleFactor: PromiseOrValue<BigNumberish>;
  totalSupply: PromiseOrValue<BigNumberish>;
  maxTotalSupply: PromiseOrValue<BigNumberish>;
  scaledTotalSupply: PromiseOrValue<BigNumberish>;
  totalAssets: PromiseOrValue<BigNumberish>;
  lastAccruedProtocolFees: PromiseOrValue<BigNumberish>;
  normalizedUnclaimedWithdrawals: PromiseOrValue<BigNumberish>;
  scaledPendingWithdrawals: PromiseOrValue<BigNumberish>;
  pendingWithdrawalExpiry: PromiseOrValue<BigNumberish>;
  isDelinquent: PromiseOrValue<boolean>;
  timeDelinquent: PromiseOrValue<BigNumberish>;
  lastInterestAccruedTimestamp: PromiseOrValue<BigNumberish>;
  unpaidWithdrawalBatchExpiries: PromiseOrValue<BigNumberish>[];
  coverageLiquidity: PromiseOrValue<BigNumberish>;
};

export type MarketDataV21StructOutput = {
  marketToken: TokenMetadataStructOutput;
  underlyingToken: TokenMetadataStructOutput;
  hooksFactory: string;
  borrower: string;
  hooksConfig: MarketHooksDataV21StructOutput;
  withdrawalBatchDuration: BigNumber;
  feeRecipient: string;
  delinquencyFeeBips: BigNumber;
  delinquencyGracePeriod: BigNumber;
  hooks: HooksInstanceDataV21StructOutput;
  temporaryReserveRatio: boolean;
  originalAnnualInterestBips: BigNumber;
  originalReserveRatioBips: BigNumber;
  temporaryReserveRatioExpiry: BigNumber;
  isClosed: boolean;
  protocolFeeBips: BigNumber;
  reserveRatioBips: BigNumber;
  annualInterestBips: BigNumber;
  scaleFactor: BigNumber;
  totalSupply: BigNumber;
  maxTotalSupply: BigNumber;
  scaledTotalSupply: BigNumber;
  totalAssets: BigNumber;
  lastAccruedProtocolFees: BigNumber;
  normalizedUnclaimedWithdrawals: BigNumber;
  scaledPendingWithdrawals: BigNumber;
  pendingWithdrawalExpiry: BigNumber;
  isDelinquent: boolean;
  timeDelinquent: BigNumber;
  lastInterestAccruedTimestamp: BigNumber;
  unpaidWithdrawalBatchExpiries: number[];
  coverageLiquidity: BigNumber;
};

export type HooksDataForBorrowerV21Struct = {
  borrower: PromiseOrValue<string>;
  isRegisteredBorrower: PromiseOrValue<boolean>;
  hooksTemplates: HooksTemplateDataV21Struct[];
  hooksInstances: HooksInstanceDataV21Struct[];
};

export type HooksDataForBorrowerV21StructOutput = {
  borrower: string;
  isRegisteredBorrower: boolean;
  hooksTemplates: HooksTemplateDataV21StructOutput[];
  hooksInstances: HooksInstanceDataV21StructOutput[];
};

export type LenderAccountDataV21Struct = {
  lender: PromiseOrValue<string>;
  scaledBalance: PromiseOrValue<BigNumberish>;
  normalizedBalance: PromiseOrValue<BigNumberish>;
  underlyingBalance: PromiseOrValue<BigNumberish>;
  underlyingApproval: PromiseOrValue<BigNumberish>;
  isBlockedFromDeposits: PromiseOrValue<boolean>;
  lastProvider: RoleProviderDataV21Struct;
  canRefresh: PromiseOrValue<boolean>;
  lastApprovalTimestamp: PromiseOrValue<BigNumberish>;
  isKnownLender: PromiseOrValue<boolean>;
};

export type LenderAccountDataV21StructOutput = {
  lender: string;
  scaledBalance: BigNumber;
  normalizedBalance: BigNumber;
  underlyingBalance: BigNumber;
  underlyingApproval: BigNumber;
  isBlockedFromDeposits: boolean;
  lastProvider: RoleProviderDataV21StructOutput;
  canRefresh: boolean;
  lastApprovalTimestamp: number;
  isKnownLender: boolean;
};

export type MarketDataWithLenderStatusV21Struct = {
  market: MarketDataV21Struct;
  lenderStatus: LenderAccountDataV21Struct;
};

export type MarketDataWithLenderStatusV21StructOutput = {
  market: MarketDataV21StructOutput;
  lenderStatus: LenderAccountDataV21StructOutput;
};

export type WithdrawalBatchDataStruct = {
  expiry: PromiseOrValue<BigNumberish>;
  status: PromiseOrValue<BigNumberish>;
  scaledTotalAmount: PromiseOrValue<BigNumberish>;
  scaledAmountBurned: PromiseOrValue<BigNumberish>;
  normalizedAmountPaid: PromiseOrValue<BigNumberish>;
  normalizedTotalAmount: PromiseOrValue<BigNumberish>;
};

export type WithdrawalBatchDataStructOutput = {
  expiry: number;
  status: number;
  scaledTotalAmount: BigNumber;
  scaledAmountBurned: BigNumber;
  normalizedAmountPaid: BigNumber;
  normalizedTotalAmount: BigNumber;
};

export type WithdrawalBatchLenderStatusStruct = {
  lender: PromiseOrValue<string>;
  scaledAmount: PromiseOrValue<BigNumberish>;
  normalizedAmountWithdrawn: PromiseOrValue<BigNumberish>;
  normalizedAmountOwed: PromiseOrValue<BigNumberish>;
  availableWithdrawalAmount: PromiseOrValue<BigNumberish>;
};

export type WithdrawalBatchLenderStatusStructOutput = {
  lender: string;
  scaledAmount: BigNumber;
  normalizedAmountWithdrawn: BigNumber;
  normalizedAmountOwed: BigNumber;
  availableWithdrawalAmount: BigNumber;
};

export type WithdrawalBatchDataWithLenderStatusV21Struct = {
  batch: WithdrawalBatchDataStruct;
  lenderStatus: WithdrawalBatchLenderStatusStruct;
};

export type WithdrawalBatchDataWithLenderStatusV21StructOutput = {
  batch: WithdrawalBatchDataStructOutput;
  lenderStatus: WithdrawalBatchLenderStatusStructOutput;
};

export type LenderAccountQueryV21Struct = {
  lender: PromiseOrValue<string>;
  market: PromiseOrValue<string>;
  withdrawalBatchExpiries: PromiseOrValue<BigNumberish>[];
};

export type LenderAccountQueryV21StructOutput = {
  lender: string;
  market: string;
  withdrawalBatchExpiries: number[];
};

export type LenderAccountQueryResultV21Struct = {
  market: MarketDataV21Struct;
  lenderStatus: LenderAccountDataV21Struct;
  withdrawalBatches: WithdrawalBatchDataWithLenderStatusV21Struct[];
};

export type LenderAccountQueryResultV21StructOutput = {
  market: MarketDataV21StructOutput;
  lenderStatus: LenderAccountDataV21StructOutput;
  withdrawalBatches: WithdrawalBatchDataWithLenderStatusV21StructOutput[];
};

export interface MarketLensV21Interface extends utils.Interface {
  functions: {
    "archController()": FunctionFragment;
    "getAllHooksTemplatesForBorrower(address)": FunctionFragment;
    "getAllMarketsDataForHooksTemplate(address)": FunctionFragment;
    "getHooksDataForBorrower(address)": FunctionFragment;
    "getHooksInstancesForBorrower(address)": FunctionFragment;
    "getHooksTemplateForBorrower(address,address)": FunctionFragment;
    "getHooksTemplatesForBorrower(address,address[])": FunctionFragment;
    "getLenderAccountData(address,address)": FunctionFragment;
    "getLenderAccountData(address,address[])": FunctionFragment;
    "getLenderAccountsData(address,address[])": FunctionFragment;
    "getMarketData(address)": FunctionFragment;
    "getMarketDataWithLenderStatus(address,address)": FunctionFragment;
    "getMarketsData(address[])": FunctionFragment;
    "getMarketsDataWithLenderStatus(address,address[])": FunctionFragment;
    "getMarketsForHooksTemplateCount(address)": FunctionFragment;
    "getPaginatedMarketsDataForHooksTemplate(address,uint256,uint256)": FunctionFragment;
    "getTokenInfo(address)": FunctionFragment;
    "getTokensInfo(address[])": FunctionFragment;
    "getWithdrawalBatchData(address,uint32)": FunctionFragment;
    "getWithdrawalBatchDataWithLenderStatus(address,uint32,address)": FunctionFragment;
    "getWithdrawalBatchDataWithLendersStatus(address,uint32,address[])": FunctionFragment;
    "getWithdrawalBatchesData(address,uint32[])": FunctionFragment;
    "getWithdrawalBatchesDataWithLenderStatus(address,uint32[],address)": FunctionFragment;
    "queryLenderAccount((address,address,uint32[]))": FunctionFragment;
    "queryLenderAccounts((address,address,uint32[])[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "archController"
      | "getAllHooksTemplatesForBorrower"
      | "getAllMarketsDataForHooksTemplate"
      | "getHooksDataForBorrower"
      | "getHooksInstancesForBorrower"
      | "getHooksTemplateForBorrower"
      | "getHooksTemplatesForBorrower"
      | "getLenderAccountData(address,address)"
      | "getLenderAccountData(address,address[])"
      | "getLenderAccountsData"
      | "getMarketData"
      | "getMarketDataWithLenderStatus"
      | "getMarketsData"
      | "getMarketsDataWithLenderStatus"
      | "getMarketsForHooksTemplateCount"
      | "getPaginatedMarketsDataForHooksTemplate"
      | "getTokenInfo"
      | "getTokensInfo"
      | "getWithdrawalBatchData"
      | "getWithdrawalBatchDataWithLenderStatus"
      | "getWithdrawalBatchDataWithLendersStatus"
      | "getWithdrawalBatchesData"
      | "getWithdrawalBatchesDataWithLenderStatus"
      | "queryLenderAccount"
      | "queryLenderAccounts"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "archController",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllHooksTemplatesForBorrower",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllMarketsDataForHooksTemplate",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getHooksDataForBorrower",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getHooksInstancesForBorrower",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getHooksTemplateForBorrower",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getHooksTemplatesForBorrower",
    values: [PromiseOrValue<string>, PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getLenderAccountData(address,address)",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getLenderAccountData(address,address[])",
    values: [PromiseOrValue<string>, PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getLenderAccountsData",
    values: [PromiseOrValue<string>, PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketData",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketDataWithLenderStatus",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketsData",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketsDataWithLenderStatus",
    values: [PromiseOrValue<string>, PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketsForHooksTemplateCount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaginatedMarketsDataForHooksTemplate",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenInfo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokensInfo",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawalBatchData",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawalBatchDataWithLenderStatus",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawalBatchDataWithLendersStatus",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawalBatchesData",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawalBatchesDataWithLenderStatus",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "queryLenderAccount",
    values: [LenderAccountQueryV21Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "queryLenderAccounts",
    values: [LenderAccountQueryV21Struct[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "archController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllHooksTemplatesForBorrower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllMarketsDataForHooksTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHooksDataForBorrower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHooksInstancesForBorrower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHooksTemplateForBorrower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHooksTemplatesForBorrower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLenderAccountData(address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLenderAccountData(address,address[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLenderAccountsData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketDataWithLenderStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketsData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketsDataWithLenderStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketsForHooksTemplateCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaginatedMarketsDataForHooksTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokensInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawalBatchData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawalBatchDataWithLenderStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawalBatchDataWithLendersStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawalBatchesData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawalBatchesDataWithLenderStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queryLenderAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queryLenderAccounts",
    data: BytesLike
  ): Result;

  events: {};
}

export interface MarketLensV21 extends BaseContract {
  contractName: "MarketLensV21";

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MarketLensV21Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    archController(overrides?: CallOverrides): Promise<[string]>;

    getAllHooksTemplatesForBorrower(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [HooksTemplateDataV21StructOutput[]] & {
        data: HooksTemplateDataV21StructOutput[];
      }
    >;

    getAllMarketsDataForHooksTemplate(
      hooksTemplate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [MarketDataV21StructOutput[]] & { data: MarketDataV21StructOutput[] }
    >;

    getHooksDataForBorrower(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [HooksDataForBorrowerV21StructOutput] & {
        data: HooksDataForBorrowerV21StructOutput;
      }
    >;

    getHooksInstancesForBorrower(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [HooksInstanceDataV21StructOutput[]] & {
        arr: HooksInstanceDataV21StructOutput[];
      }
    >;

    getHooksTemplateForBorrower(
      borrower: PromiseOrValue<string>,
      hooksTemplate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [HooksTemplateDataV21StructOutput] & {
        data: HooksTemplateDataV21StructOutput;
      }
    >;

    getHooksTemplatesForBorrower(
      borrower: PromiseOrValue<string>,
      hooksTemplates: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<
      [HooksTemplateDataV21StructOutput[]] & {
        data: HooksTemplateDataV21StructOutput[];
      }
    >;

    "getLenderAccountData(address,address)"(
      lender: PromiseOrValue<string>,
      market: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [LenderAccountDataV21StructOutput] & {
        data: LenderAccountDataV21StructOutput;
      }
    >;

    "getLenderAccountData(address,address[])"(
      lender: PromiseOrValue<string>,
      markets: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<
      [LenderAccountDataV21StructOutput[]] & {
        arr: LenderAccountDataV21StructOutput[];
      }
    >;

    getLenderAccountsData(
      market: PromiseOrValue<string>,
      lenders: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<
      [LenderAccountDataV21StructOutput[]] & {
        data: LenderAccountDataV21StructOutput[];
      }
    >;

    getMarketData(
      market: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [MarketDataV21StructOutput] & { data: MarketDataV21StructOutput }
    >;

    getMarketDataWithLenderStatus(
      lender: PromiseOrValue<string>,
      market: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [MarketDataWithLenderStatusV21StructOutput] & {
        data: MarketDataWithLenderStatusV21StructOutput;
      }
    >;

    getMarketsData(
      markets: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<
      [MarketDataV21StructOutput[]] & { data: MarketDataV21StructOutput[] }
    >;

    getMarketsDataWithLenderStatus(
      lender: PromiseOrValue<string>,
      markets: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<
      [MarketDataWithLenderStatusV21StructOutput[]] & {
        data: MarketDataWithLenderStatusV21StructOutput[];
      }
    >;

    getMarketsForHooksTemplateCount(
      hooksTemplate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPaginatedMarketsDataForHooksTemplate(
      hooksTemplate: PromiseOrValue<string>,
      start: PromiseOrValue<BigNumberish>,
      end: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [MarketDataV21StructOutput[]] & { data: MarketDataV21StructOutput[] }
    >;

    getTokenInfo(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [TokenMetadataStructOutput] & { info: TokenMetadataStructOutput }
    >;

    getTokensInfo(
      tokens: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<
      [TokenMetadataStructOutput[]] & { info: TokenMetadataStructOutput[] }
    >;

    getWithdrawalBatchData(
      market: PromiseOrValue<string>,
      expiry: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [WithdrawalBatchDataStructOutput] & {
        data: WithdrawalBatchDataStructOutput;
      }
    >;

    getWithdrawalBatchDataWithLenderStatus(
      market: PromiseOrValue<string>,
      expiry: PromiseOrValue<BigNumberish>,
      lender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [WithdrawalBatchDataWithLenderStatusV21StructOutput] & {
        status: WithdrawalBatchDataWithLenderStatusV21StructOutput;
      }
    >;

    getWithdrawalBatchDataWithLendersStatus(
      market: PromiseOrValue<string>,
      expiry: PromiseOrValue<BigNumberish>,
      lenders: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<
      [
        WithdrawalBatchDataStructOutput,
        WithdrawalBatchLenderStatusStructOutput[]
      ] & {
        batch: WithdrawalBatchDataStructOutput;
        statuses: WithdrawalBatchLenderStatusStructOutput[];
      }
    >;

    getWithdrawalBatchesData(
      market: PromiseOrValue<string>,
      expiries: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<
      [WithdrawalBatchDataStructOutput[]] & {
        data: WithdrawalBatchDataStructOutput[];
      }
    >;

    getWithdrawalBatchesDataWithLenderStatus(
      market: PromiseOrValue<string>,
      expiries: PromiseOrValue<BigNumberish>[],
      lender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [WithdrawalBatchDataWithLenderStatusV21StructOutput[]] & {
        statuses: WithdrawalBatchDataWithLenderStatusV21StructOutput[];
      }
    >;

    queryLenderAccount(
      query: LenderAccountQueryV21Struct,
      overrides?: CallOverrides
    ): Promise<
      [LenderAccountQueryResultV21StructOutput] & {
        result: LenderAccountQueryResultV21StructOutput;
      }
    >;

    queryLenderAccounts(
      queries: LenderAccountQueryV21Struct[],
      overrides?: CallOverrides
    ): Promise<
      [LenderAccountQueryResultV21StructOutput[]] & {
        result: LenderAccountQueryResultV21StructOutput[];
      }
    >;
  };

  archController(overrides?: CallOverrides): Promise<string>;

  getAllHooksTemplatesForBorrower(
    borrower: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<HooksTemplateDataV21StructOutput[]>;

  getAllMarketsDataForHooksTemplate(
    hooksTemplate: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<MarketDataV21StructOutput[]>;

  getHooksDataForBorrower(
    borrower: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<HooksDataForBorrowerV21StructOutput>;

  getHooksInstancesForBorrower(
    borrower: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<HooksInstanceDataV21StructOutput[]>;

  getHooksTemplateForBorrower(
    borrower: PromiseOrValue<string>,
    hooksTemplate: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<HooksTemplateDataV21StructOutput>;

  getHooksTemplatesForBorrower(
    borrower: PromiseOrValue<string>,
    hooksTemplates: PromiseOrValue<string>[],
    overrides?: CallOverrides
  ): Promise<HooksTemplateDataV21StructOutput[]>;

  "getLenderAccountData(address,address)"(
    lender: PromiseOrValue<string>,
    market: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<LenderAccountDataV21StructOutput>;

  "getLenderAccountData(address,address[])"(
    lender: PromiseOrValue<string>,
    markets: PromiseOrValue<string>[],
    overrides?: CallOverrides
  ): Promise<LenderAccountDataV21StructOutput[]>;

  getLenderAccountsData(
    market: PromiseOrValue<string>,
    lenders: PromiseOrValue<string>[],
    overrides?: CallOverrides
  ): Promise<LenderAccountDataV21StructOutput[]>;

  getMarketData(
    market: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<MarketDataV21StructOutput>;

  getMarketDataWithLenderStatus(
    lender: PromiseOrValue<string>,
    market: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<MarketDataWithLenderStatusV21StructOutput>;

  getMarketsData(
    markets: PromiseOrValue<string>[],
    overrides?: CallOverrides
  ): Promise<MarketDataV21StructOutput[]>;

  getMarketsDataWithLenderStatus(
    lender: PromiseOrValue<string>,
    markets: PromiseOrValue<string>[],
    overrides?: CallOverrides
  ): Promise<MarketDataWithLenderStatusV21StructOutput[]>;

  getMarketsForHooksTemplateCount(
    hooksTemplate: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPaginatedMarketsDataForHooksTemplate(
    hooksTemplate: PromiseOrValue<string>,
    start: PromiseOrValue<BigNumberish>,
    end: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<MarketDataV21StructOutput[]>;

  getTokenInfo(
    token: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<TokenMetadataStructOutput>;

  getTokensInfo(
    tokens: PromiseOrValue<string>[],
    overrides?: CallOverrides
  ): Promise<TokenMetadataStructOutput[]>;

  getWithdrawalBatchData(
    market: PromiseOrValue<string>,
    expiry: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<WithdrawalBatchDataStructOutput>;

  getWithdrawalBatchDataWithLenderStatus(
    market: PromiseOrValue<string>,
    expiry: PromiseOrValue<BigNumberish>,
    lender: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<WithdrawalBatchDataWithLenderStatusV21StructOutput>;

  getWithdrawalBatchDataWithLendersStatus(
    market: PromiseOrValue<string>,
    expiry: PromiseOrValue<BigNumberish>,
    lenders: PromiseOrValue<string>[],
    overrides?: CallOverrides
  ): Promise<
    [
      WithdrawalBatchDataStructOutput,
      WithdrawalBatchLenderStatusStructOutput[]
    ] & {
      batch: WithdrawalBatchDataStructOutput;
      statuses: WithdrawalBatchLenderStatusStructOutput[];
    }
  >;

  getWithdrawalBatchesData(
    market: PromiseOrValue<string>,
    expiries: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<WithdrawalBatchDataStructOutput[]>;

  getWithdrawalBatchesDataWithLenderStatus(
    market: PromiseOrValue<string>,
    expiries: PromiseOrValue<BigNumberish>[],
    lender: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<WithdrawalBatchDataWithLenderStatusV21StructOutput[]>;

  queryLenderAccount(
    query: LenderAccountQueryV21Struct,
    overrides?: CallOverrides
  ): Promise<LenderAccountQueryResultV21StructOutput>;

  queryLenderAccounts(
    queries: LenderAccountQueryV21Struct[],
    overrides?: CallOverrides
  ): Promise<LenderAccountQueryResultV21StructOutput[]>;

  callStatic: {
    archController(overrides?: CallOverrides): Promise<string>;

    getAllHooksTemplatesForBorrower(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<HooksTemplateDataV21StructOutput[]>;

    getAllMarketsDataForHooksTemplate(
      hooksTemplate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<MarketDataV21StructOutput[]>;

    getHooksDataForBorrower(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<HooksDataForBorrowerV21StructOutput>;

    getHooksInstancesForBorrower(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<HooksInstanceDataV21StructOutput[]>;

    getHooksTemplateForBorrower(
      borrower: PromiseOrValue<string>,
      hooksTemplate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<HooksTemplateDataV21StructOutput>;

    getHooksTemplatesForBorrower(
      borrower: PromiseOrValue<string>,
      hooksTemplates: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<HooksTemplateDataV21StructOutput[]>;

    "getLenderAccountData(address,address)"(
      lender: PromiseOrValue<string>,
      market: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<LenderAccountDataV21StructOutput>;

    "getLenderAccountData(address,address[])"(
      lender: PromiseOrValue<string>,
      markets: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<LenderAccountDataV21StructOutput[]>;

    getLenderAccountsData(
      market: PromiseOrValue<string>,
      lenders: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<LenderAccountDataV21StructOutput[]>;

    getMarketData(
      market: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<MarketDataV21StructOutput>;

    getMarketDataWithLenderStatus(
      lender: PromiseOrValue<string>,
      market: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<MarketDataWithLenderStatusV21StructOutput>;

    getMarketsData(
      markets: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<MarketDataV21StructOutput[]>;

    getMarketsDataWithLenderStatus(
      lender: PromiseOrValue<string>,
      markets: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<MarketDataWithLenderStatusV21StructOutput[]>;

    getMarketsForHooksTemplateCount(
      hooksTemplate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPaginatedMarketsDataForHooksTemplate(
      hooksTemplate: PromiseOrValue<string>,
      start: PromiseOrValue<BigNumberish>,
      end: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<MarketDataV21StructOutput[]>;

    getTokenInfo(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<TokenMetadataStructOutput>;

    getTokensInfo(
      tokens: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<TokenMetadataStructOutput[]>;

    getWithdrawalBatchData(
      market: PromiseOrValue<string>,
      expiry: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<WithdrawalBatchDataStructOutput>;

    getWithdrawalBatchDataWithLenderStatus(
      market: PromiseOrValue<string>,
      expiry: PromiseOrValue<BigNumberish>,
      lender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<WithdrawalBatchDataWithLenderStatusV21StructOutput>;

    getWithdrawalBatchDataWithLendersStatus(
      market: PromiseOrValue<string>,
      expiry: PromiseOrValue<BigNumberish>,
      lenders: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<
      [
        WithdrawalBatchDataStructOutput,
        WithdrawalBatchLenderStatusStructOutput[]
      ] & {
        batch: WithdrawalBatchDataStructOutput;
        statuses: WithdrawalBatchLenderStatusStructOutput[];
      }
    >;

    getWithdrawalBatchesData(
      market: PromiseOrValue<string>,
      expiries: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<WithdrawalBatchDataStructOutput[]>;

    getWithdrawalBatchesDataWithLenderStatus(
      market: PromiseOrValue<string>,
      expiries: PromiseOrValue<BigNumberish>[],
      lender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<WithdrawalBatchDataWithLenderStatusV21StructOutput[]>;

    queryLenderAccount(
      query: LenderAccountQueryV21Struct,
      overrides?: CallOverrides
    ): Promise<LenderAccountQueryResultV21StructOutput>;

    queryLenderAccounts(
      queries: LenderAccountQueryV21Struct[],
      overrides?: CallOverrides
    ): Promise<LenderAccountQueryResultV21StructOutput[]>;
  };

  filters: {};

  estimateGas: {
    archController(overrides?: CallOverrides): Promise<BigNumber>;

    getAllHooksTemplatesForBorrower(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllMarketsDataForHooksTemplate(
      hooksTemplate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getHooksDataForBorrower(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getHooksInstancesForBorrower(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getHooksTemplateForBorrower(
      borrower: PromiseOrValue<string>,
      hooksTemplate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getHooksTemplatesForBorrower(
      borrower: PromiseOrValue<string>,
      hooksTemplates: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getLenderAccountData(address,address)"(
      lender: PromiseOrValue<string>,
      market: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getLenderAccountData(address,address[])"(
      lender: PromiseOrValue<string>,
      markets: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLenderAccountsData(
      market: PromiseOrValue<string>,
      lenders: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarketData(
      market: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarketDataWithLenderStatus(
      lender: PromiseOrValue<string>,
      market: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarketsData(
      markets: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarketsDataWithLenderStatus(
      lender: PromiseOrValue<string>,
      markets: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarketsForHooksTemplateCount(
      hooksTemplate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPaginatedMarketsDataForHooksTemplate(
      hooksTemplate: PromiseOrValue<string>,
      start: PromiseOrValue<BigNumberish>,
      end: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokenInfo(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokensInfo(
      tokens: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWithdrawalBatchData(
      market: PromiseOrValue<string>,
      expiry: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWithdrawalBatchDataWithLenderStatus(
      market: PromiseOrValue<string>,
      expiry: PromiseOrValue<BigNumberish>,
      lender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWithdrawalBatchDataWithLendersStatus(
      market: PromiseOrValue<string>,
      expiry: PromiseOrValue<BigNumberish>,
      lenders: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWithdrawalBatchesData(
      market: PromiseOrValue<string>,
      expiries: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWithdrawalBatchesDataWithLenderStatus(
      market: PromiseOrValue<string>,
      expiries: PromiseOrValue<BigNumberish>[],
      lender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    queryLenderAccount(
      query: LenderAccountQueryV21Struct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    queryLenderAccounts(
      queries: LenderAccountQueryV21Struct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    archController(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAllHooksTemplatesForBorrower(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAllMarketsDataForHooksTemplate(
      hooksTemplate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getHooksDataForBorrower(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getHooksInstancesForBorrower(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getHooksTemplateForBorrower(
      borrower: PromiseOrValue<string>,
      hooksTemplate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getHooksTemplatesForBorrower(
      borrower: PromiseOrValue<string>,
      hooksTemplates: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getLenderAccountData(address,address)"(
      lender: PromiseOrValue<string>,
      market: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getLenderAccountData(address,address[])"(
      lender: PromiseOrValue<string>,
      markets: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLenderAccountsData(
      market: PromiseOrValue<string>,
      lenders: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarketData(
      market: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarketDataWithLenderStatus(
      lender: PromiseOrValue<string>,
      market: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarketsData(
      markets: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarketsDataWithLenderStatus(
      lender: PromiseOrValue<string>,
      markets: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarketsForHooksTemplateCount(
      hooksTemplate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPaginatedMarketsDataForHooksTemplate(
      hooksTemplate: PromiseOrValue<string>,
      start: PromiseOrValue<BigNumberish>,
      end: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokenInfo(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokensInfo(
      tokens: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWithdrawalBatchData(
      market: PromiseOrValue<string>,
      expiry: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWithdrawalBatchDataWithLenderStatus(
      market: PromiseOrValue<string>,
      expiry: PromiseOrValue<BigNumberish>,
      lender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWithdrawalBatchDataWithLendersStatus(
      market: PromiseOrValue<string>,
      expiry: PromiseOrValue<BigNumberish>,
      lenders: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWithdrawalBatchesData(
      market: PromiseOrValue<string>,
      expiries: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWithdrawalBatchesDataWithLenderStatus(
      market: PromiseOrValue<string>,
      expiries: PromiseOrValue<BigNumberish>[],
      lender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    queryLenderAccount(
      query: LenderAccountQueryV21Struct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    queryLenderAccounts(
      queries: LenderAccountQueryV21Struct[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
