/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type DepositorStruct = {
  shares: PromiseOrValue<BigNumberish>;
  lastFullLiquidationIndex: PromiseOrValue<BigNumberish>;
};

export type DepositorStructOutput = {
  shares: BigNumber;
  lastFullLiquidationIndex: number;
};

export interface SimpleMarketCollateralInterface extends utils.Interface {
  functions: {
    "LIQUIDATION_COOLDOWN()": FunctionFragment;
    "availableCollateral()": FunctionFragment;
    "bebopSettlementContract()": FunctionFragment;
    "collateralAsset()": FunctionFragment;
    "deposit(uint256)": FunctionFragment;
    "factory()": FunctionFragment;
    "fullLiquidationIndex()": FunctionFragment;
    "getDepositor(address)": FunctionFragment;
    "getMarketDelinquencyStatus()": FunctionFragment;
    "getReclaimableAmount(address)": FunctionFragment;
    "liquidateCollateral(address,bytes,uint256,uint256,uint256)": FunctionFragment;
    "market()": FunctionFragment;
    "marketBorrower()": FunctionFragment;
    "maxRepaymentBips()": FunctionFragment;
    "name()": FunctionFragment;
    "nextLiquidationTrigger()": FunctionFragment;
    "reclaimCollateral()": FunctionFragment;
    "rescueTokens(address)": FunctionFragment;
    "sharesOf(address)": FunctionFragment;
    "totalShares()": FunctionFragment;
    "underlyingAsset()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "LIQUIDATION_COOLDOWN"
      | "availableCollateral"
      | "bebopSettlementContract"
      | "collateralAsset"
      | "deposit"
      | "factory"
      | "fullLiquidationIndex"
      | "getDepositor"
      | "getMarketDelinquencyStatus"
      | "getReclaimableAmount"
      | "liquidateCollateral"
      | "market"
      | "marketBorrower"
      | "maxRepaymentBips"
      | "name"
      | "nextLiquidationTrigger"
      | "reclaimCollateral"
      | "rescueTokens"
      | "sharesOf"
      | "totalShares"
      | "underlyingAsset"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "LIQUIDATION_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "availableCollateral",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bebopSettlementContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collateralAsset",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fullLiquidationIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositor",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketDelinquencyStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReclaimableAmount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidateCollateral",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "market", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "marketBorrower",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxRepaymentBips",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextLiquidationTrigger",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reclaimCollateral",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rescueTokens",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "sharesOf",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "totalShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "underlyingAsset",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "LIQUIDATION_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "availableCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bebopSettlementContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fullLiquidationIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketDelinquencyStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReclaimableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidateCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "market", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketBorrower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxRepaymentBips",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextLiquidationTrigger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reclaimCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rescueTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sharesOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "underlyingAsset",
    data: BytesLike
  ): Result;

  events: {};
}

export interface SimpleMarketCollateral extends BaseContract {
  contractName: "SimpleMarketCollateral";

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SimpleMarketCollateralInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    LIQUIDATION_COOLDOWN(overrides?: CallOverrides): Promise<[number]>;

    availableCollateral(overrides?: CallOverrides): Promise<[BigNumber]>;

    bebopSettlementContract(overrides?: CallOverrides): Promise<[string]>;

    collateralAsset(overrides?: CallOverrides): Promise<[string]>;

    deposit(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    fullLiquidationIndex(overrides?: CallOverrides): Promise<[number]>;

    getDepositor(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[DepositorStructOutput] & { depositor: DepositorStructOutput }>;

    getMarketDelinquencyStatus(
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber] & {
        marketInPenalty: boolean;
        delinquentDebt: BigNumber;
      }
    >;

    getReclaimableAmount(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    liquidateCollateral(
      exchange: PromiseOrValue<string>,
      quoteCalldata: PromiseOrValue<BytesLike>,
      lengthWithdrawalQueue: PromiseOrValue<BigNumberish>,
      maxCollateralToLiquidate: PromiseOrValue<BigNumberish>,
      minUnderlyingOut: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    market(overrides?: CallOverrides): Promise<[string]>;

    marketBorrower(overrides?: CallOverrides): Promise<[string]>;

    maxRepaymentBips(overrides?: CallOverrides): Promise<[number]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    nextLiquidationTrigger(overrides?: CallOverrides): Promise<[number]>;

    reclaimCollateral(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    rescueTokens(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sharesOf(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    totalShares(overrides?: CallOverrides): Promise<[BigNumber]>;

    underlyingAsset(overrides?: CallOverrides): Promise<[string]>;
  };

  LIQUIDATION_COOLDOWN(overrides?: CallOverrides): Promise<number>;

  availableCollateral(overrides?: CallOverrides): Promise<BigNumber>;

  bebopSettlementContract(overrides?: CallOverrides): Promise<string>;

  collateralAsset(overrides?: CallOverrides): Promise<string>;

  deposit(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  factory(overrides?: CallOverrides): Promise<string>;

  fullLiquidationIndex(overrides?: CallOverrides): Promise<number>;

  getDepositor(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<DepositorStructOutput>;

  getMarketDelinquencyStatus(
    overrides?: CallOverrides
  ): Promise<
    [boolean, BigNumber] & {
      marketInPenalty: boolean;
      delinquentDebt: BigNumber;
    }
  >;

  getReclaimableAmount(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  liquidateCollateral(
    exchange: PromiseOrValue<string>,
    quoteCalldata: PromiseOrValue<BytesLike>,
    lengthWithdrawalQueue: PromiseOrValue<BigNumberish>,
    maxCollateralToLiquidate: PromiseOrValue<BigNumberish>,
    minUnderlyingOut: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  market(overrides?: CallOverrides): Promise<string>;

  marketBorrower(overrides?: CallOverrides): Promise<string>;

  maxRepaymentBips(overrides?: CallOverrides): Promise<number>;

  name(overrides?: CallOverrides): Promise<string>;

  nextLiquidationTrigger(overrides?: CallOverrides): Promise<number>;

  reclaimCollateral(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  rescueTokens(
    token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sharesOf(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  totalShares(overrides?: CallOverrides): Promise<BigNumber>;

  underlyingAsset(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    LIQUIDATION_COOLDOWN(overrides?: CallOverrides): Promise<number>;

    availableCollateral(overrides?: CallOverrides): Promise<BigNumber>;

    bebopSettlementContract(overrides?: CallOverrides): Promise<string>;

    collateralAsset(overrides?: CallOverrides): Promise<string>;

    deposit(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    factory(overrides?: CallOverrides): Promise<string>;

    fullLiquidationIndex(overrides?: CallOverrides): Promise<number>;

    getDepositor(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<DepositorStructOutput>;

    getMarketDelinquencyStatus(
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber] & {
        marketInPenalty: boolean;
        delinquentDebt: BigNumber;
      }
    >;

    getReclaimableAmount(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidateCollateral(
      exchange: PromiseOrValue<string>,
      quoteCalldata: PromiseOrValue<BytesLike>,
      lengthWithdrawalQueue: PromiseOrValue<BigNumberish>,
      maxCollateralToLiquidate: PromiseOrValue<BigNumberish>,
      minUnderlyingOut: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    market(overrides?: CallOverrides): Promise<string>;

    marketBorrower(overrides?: CallOverrides): Promise<string>;

    maxRepaymentBips(overrides?: CallOverrides): Promise<number>;

    name(overrides?: CallOverrides): Promise<string>;

    nextLiquidationTrigger(overrides?: CallOverrides): Promise<number>;

    reclaimCollateral(overrides?: CallOverrides): Promise<void>;

    rescueTokens(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    sharesOf(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalShares(overrides?: CallOverrides): Promise<BigNumber>;

    underlyingAsset(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    LIQUIDATION_COOLDOWN(overrides?: CallOverrides): Promise<BigNumber>;

    availableCollateral(overrides?: CallOverrides): Promise<BigNumber>;

    bebopSettlementContract(overrides?: CallOverrides): Promise<BigNumber>;

    collateralAsset(overrides?: CallOverrides): Promise<BigNumber>;

    deposit(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    fullLiquidationIndex(overrides?: CallOverrides): Promise<BigNumber>;

    getDepositor(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarketDelinquencyStatus(overrides?: CallOverrides): Promise<BigNumber>;

    getReclaimableAmount(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidateCollateral(
      exchange: PromiseOrValue<string>,
      quoteCalldata: PromiseOrValue<BytesLike>,
      lengthWithdrawalQueue: PromiseOrValue<BigNumberish>,
      maxCollateralToLiquidate: PromiseOrValue<BigNumberish>,
      minUnderlyingOut: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    market(overrides?: CallOverrides): Promise<BigNumber>;

    marketBorrower(overrides?: CallOverrides): Promise<BigNumber>;

    maxRepaymentBips(overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    nextLiquidationTrigger(overrides?: CallOverrides): Promise<BigNumber>;

    reclaimCollateral(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    rescueTokens(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sharesOf(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalShares(overrides?: CallOverrides): Promise<BigNumber>;

    underlyingAsset(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    LIQUIDATION_COOLDOWN(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    availableCollateral(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bebopSettlementContract(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    collateralAsset(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deposit(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fullLiquidationIndex(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDepositor(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarketDelinquencyStatus(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getReclaimableAmount(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    liquidateCollateral(
      exchange: PromiseOrValue<string>,
      quoteCalldata: PromiseOrValue<BytesLike>,
      lengthWithdrawalQueue: PromiseOrValue<BigNumberish>,
      maxCollateralToLiquidate: PromiseOrValue<BigNumberish>,
      minUnderlyingOut: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    market(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    marketBorrower(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxRepaymentBips(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nextLiquidationTrigger(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    reclaimCollateral(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    rescueTokens(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sharesOf(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalShares(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    underlyingAsset(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
