/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface WildcatCollateralFactoryInterface extends utils.Interface {
  functions: {
    "approveExecutor(address)": FunctionFragment;
    "archController()": FunctionFragment;
    "collateralContractList(address,uint256)": FunctionFragment;
    "collateralInitCodeHash()": FunctionFragment;
    "collateralInitCodeStorage()": FunctionFragment;
    "deployCollateralContract(address,address)": FunctionFragment;
    "isApprovedExecutor(address)": FunctionFragment;
    "listCollateralMarkets(address,address)": FunctionFragment;
    "name()": FunctionFragment;
    "removeExecutor(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "approveExecutor"
      | "archController"
      | "collateralContractList"
      | "collateralInitCodeHash"
      | "collateralInitCodeStorage"
      | "deployCollateralContract"
      | "isApprovedExecutor"
      | "listCollateralMarkets"
      | "name"
      | "removeExecutor"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "approveExecutor",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "archController",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collateralContractList",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "collateralInitCodeHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collateralInitCodeStorage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployCollateralContract",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedExecutor",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "listCollateralMarkets",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeExecutor",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "archController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralContractList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralInitCodeHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralInitCodeStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployCollateralContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listCollateralMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeExecutor",
    data: BytesLike
  ): Result;

  events: {};
}

export interface WildcatCollateralFactory extends BaseContract {
  contractName: "WildcatCollateralFactory";

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: WildcatCollateralFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    approveExecutor(
      _executor: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    archController(overrides?: CallOverrides): Promise<[string]>;

    collateralContractList(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string] & {
        collateralContractAddress: string;
        collateralToken: string;
        associatedMarket: string;
      }
    >;

    collateralInitCodeHash(overrides?: CallOverrides): Promise<[BigNumber]>;

    collateralInitCodeStorage(overrides?: CallOverrides): Promise<[string]>;

    deployCollateralContract(
      _collateralToken: PromiseOrValue<string>,
      _associatedMarket: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isApprovedExecutor(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    listCollateralMarkets(
      _market: PromiseOrValue<string>,
      _asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    removeExecutor(
      _executor: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  approveExecutor(
    _executor: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  archController(overrides?: CallOverrides): Promise<string>;

  collateralContractList(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string] & {
      collateralContractAddress: string;
      collateralToken: string;
      associatedMarket: string;
    }
  >;

  collateralInitCodeHash(overrides?: CallOverrides): Promise<BigNumber>;

  collateralInitCodeStorage(overrides?: CallOverrides): Promise<string>;

  deployCollateralContract(
    _collateralToken: PromiseOrValue<string>,
    _associatedMarket: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isApprovedExecutor(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  listCollateralMarkets(
    _market: PromiseOrValue<string>,
    _asset: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  name(overrides?: CallOverrides): Promise<string>;

  removeExecutor(
    _executor: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    approveExecutor(
      _executor: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    archController(overrides?: CallOverrides): Promise<string>;

    collateralContractList(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string] & {
        collateralContractAddress: string;
        collateralToken: string;
        associatedMarket: string;
      }
    >;

    collateralInitCodeHash(overrides?: CallOverrides): Promise<BigNumber>;

    collateralInitCodeStorage(overrides?: CallOverrides): Promise<string>;

    deployCollateralContract(
      _collateralToken: PromiseOrValue<string>,
      _associatedMarket: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    isApprovedExecutor(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    listCollateralMarkets(
      _market: PromiseOrValue<string>,
      _asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    name(overrides?: CallOverrides): Promise<string>;

    removeExecutor(
      _executor: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    approveExecutor(
      _executor: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    archController(overrides?: CallOverrides): Promise<BigNumber>;

    collateralContractList(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    collateralInitCodeHash(overrides?: CallOverrides): Promise<BigNumber>;

    collateralInitCodeStorage(overrides?: CallOverrides): Promise<BigNumber>;

    deployCollateralContract(
      _collateralToken: PromiseOrValue<string>,
      _associatedMarket: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isApprovedExecutor(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    listCollateralMarkets(
      _market: PromiseOrValue<string>,
      _asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    removeExecutor(
      _executor: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    approveExecutor(
      _executor: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    archController(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    collateralContractList(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    collateralInitCodeHash(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    collateralInitCodeStorage(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deployCollateralContract(
      _collateralToken: PromiseOrValue<string>,
      _associatedMarket: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isApprovedExecutor(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    listCollateralMarkets(
      _market: PromiseOrValue<string>,
      _asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeExecutor(
      _executor: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
