// SPDX-License-Identifier: MIT
// Generated by scripts/sync-v2.5-protocol.js from the Sepolia v2.5.5 deploy profile.
pragma solidity ^0.8.20;

interface WildcatMarketV2_5 {
  struct MarketState {
    bool isClosed;
    uint128 maxTotalSupply;
    uint128 accruedProtocolFees;
    uint128 normalizedUnclaimedWithdrawals;
    uint104 scaledTotalSupply;
    uint104 scaledPendingWithdrawals;
    uint32 pendingWithdrawalExpiry;
    bool isDelinquent;
    uint32 timeDelinquent;
    uint16 protocolFeeBips;
    uint16 annualInterestBips;
    uint16 reserveRatioBips;
    uint112 scaleFactor;
    uint32 lastInterestAccruedTimestamp;
    uint128 withdrawalRemainder;
  }

  struct AccountWithdrawalStatus {
    uint128 scaledAmount;
    uint128 normalizedAmountWithdrawn;
  }

  struct WithdrawalBatch {
    uint128 scaledTotalAmount;
    uint128 scaledAmountBurned;
    uint128 normalizedAmountPaid;
    uint128 paymentRemainder;
  }

  function acceptBorrowerTransfer() external;

  function accruedProtocolFees() external view returns (uint256);

  function allowance(address, address) external view returns (uint256);

  function annualInterestBips() external view returns (uint256);

  function approve(address spender, uint256 amount) external returns (bool);

  function archController() external view returns (address);

  function asset() external view returns (address);

  function balanceOf(address account) external view returns (uint256);

  function borrow(uint256 amount) external;

  function borrowableAssets() external view returns (uint256);

  function borrower() external view returns (address);

  function borrowerIdentityRegistry() external view returns (address);

  function borrowerPrincipal() external view returns (address);

  function cancelBorrowerTransfer() external;

  function changeSphereXEngine(address newSphereXEngine) external;

  function closeMarket() external;

  function collectFees() external;

  function coverageLiquidity() external view returns (uint256);

  function currentState() external view returns (MarketState memory state);

  function decimals() external view returns (uint8);

  function defaultedAt() external view returns (uint256);

  function delinquencyFeeBips() external view returns (uint256);

  function delinquencyGracePeriod() external view returns (uint256);

  function deposit(uint256 amount) external;

  function depositUpTo(uint256 amount) external returns (uint256);

  function executePendingAnnualInterestBipsReduction() external;

  function executeWithdrawal(address accountAddress, uint32 expiry) external returns (uint256);

  function executeWithdrawals(address[] calldata accountAddresses, uint32[] calldata expiries) external returns (uint256[] memory amounts);

  function factory() external view returns (address);

  function feeRecipient() external view returns (address);

  function getAccountWithdrawalStatus(address accountAddress, uint32 expiry) external view returns (AccountWithdrawalStatus memory status);

  function getAvailableWithdrawalAmount(address accountAddress, uint32 expiry) external view returns (uint256);

  function getUnpaidBatchExpiries() external view returns (uint32[] memory);

  function getWithdrawalBatch(uint32 expiry) external view returns (WithdrawalBatch memory batch);

  function hooks() external view returns (uint256);

  function isClosed() external view returns (bool);

  function maxTotalSupply() external view returns (uint256);

  function maximumDeposit() external view returns (uint256);

  function name() external view returns (string memory);

  function nukeFromOrbit(address accountAddress) external;

  function pendingBorrower() external view returns (address);

  function pendingBorrowerPrincipal() external view returns (address);

  function previousState() external view returns (MarketState memory);

  function queueFullWithdrawal() external returns (uint32 expiry);

  function queueWithdrawal(uint256 amount) external returns (uint32 expiry);

  function queueWithdrawalScaled(uint256 scaledAmount) external returns (uint32 expiry);

  function registerWrapper(address wrapper) external;

  function registeredWrapper() external view returns (address);

  function repay(uint256 amount) external;

  function repayAndProcessUnpaidWithdrawalBatches(uint256 repayAmount, uint256 maxBatches) external;

  function repaymentDate() external view returns (uint256);

  function repaymentDeadline() external view returns (uint256);

  function repaymentPeriod() external view returns (uint256);

  function requestBorrowerTransfer(address newBorrower) external;

  function rescueTokens(address token) external;

  function reserveRatioBips() external view returns (uint256);

  function scaleFactor() external view returns (uint256);

  function scaledBalanceOf(address account) external view returns (uint256);

  function scaledTotalSupply() external view returns (uint256);

  function scaledTransferRounding() external pure returns (bytes32);

  function sentinel() external view returns (address);

  function setAnnualInterestAndReserveRatioBips(uint16 _annualInterestBips, uint16 _reserveRatioBips) external;

  function setMaxTotalSupply(uint256 _maxTotalSupply) external;

  function setProtocolFeeBips(uint16 _protocolFeeBips) external;

  function sphereXEngine() external view returns (address);

  function sphereXOperator() external view returns (address);

  function symbol() external view returns (string memory);

  function totalAssets() external view returns (uint256);

  function totalDebts() external view returns (uint256);

  function totalSupply() external view returns (uint256);

  function transfer(address to, uint256 amount) external returns (bool);

  function transferFrom(address from, address to, uint256 amount) external returns (bool);

  function updateState() external;

  function version() external pure returns (string memory);

  function withdrawableProtocolFees() external view returns (uint128);

  function withdrawalBatchDuration() external view returns (uint256);

  function wrapperFactory() external view returns (address);

  event AnnualInterestAndReserveRatioBipsUpdated(address indexed caller, uint256 previousAnnualInterestBips, uint256 newAnnualInterestBips, uint256 previousReserveRatioBips, uint256 newReserveRatioBips);

  event Approval(address indexed owner, address indexed spender, uint256 value);

  event Borrow(address indexed borrower, uint256 assetAmount);

  event BorrowerTransferCancelled(address indexed borrower, address indexed cancelledPendingBorrower, address borrowerPrincipal, address cancelledPendingBorrowerPrincipal);

  event BorrowerTransferRequested(address indexed borrower, address indexed previousPendingBorrower, address indexed pendingBorrower, address borrowerPrincipal, address previousPendingBorrowerPrincipal, address pendingBorrowerPrincipal);

  event BorrowerTransferred(address indexed previousBorrower, address indexed newBorrower, address previousBorrowerPrincipal, address indexed newBorrowerPrincipal);

  event ChangedSpherexEngineAddress(address oldEngineAddress, address newEngineAddress);

  event ChangedSpherexOperator(address oldSphereXAdmin, address newSphereXAdmin);

  event DebtRepaid(address indexed from, uint256 assetAmount);

  event DefaultRecorded(uint256 effectiveTimestamp);

  event Deposit(address indexed account, uint256 assetAmount, uint256 scaledAmount);

  event FeesCollected(address indexed collector, address indexed feeRecipient, uint256 assets);

  event InterestAndFeesAccrued(uint256 fromTimestamp, uint256 toTimestamp, uint256 scaleFactor, uint256 baseInterestRay, uint256 delinquencyFeeRay, uint256 protocolFees);

  event MarketClosed(address indexed borrower, uint256 timestamp);

  event MaxTotalSupplyUpdated(address indexed caller, uint256 previousMaxTotalSupply, uint256 newMaxTotalSupply);

  event ProtocolFeeBipsUpdated(address indexed caller, uint256 previousProtocolFeeBips, uint256 newProtocolFeeBips);

  event RepaymentDateReached(uint256 effectiveTimestamp);

  event SanctionedAccountAssetsQueuedForWithdrawal(address indexed account, uint256 expiry, uint256 scaledAmount, uint256 normalizedAmount);

  event SanctionedAccountWithdrawalSentToEscrow(address indexed account, address escrow, uint32 expiry, uint256 amount);

  event StateUpdated(uint256 scaleFactor, bool isDelinquent);

  event Transfer(address indexed from, address indexed to, uint256 value);

  event WithdrawalBatchClosed(uint256 indexed expiry);

  event WithdrawalBatchCreated(uint256 indexed expiry);

  event WithdrawalBatchExpired(uint256 indexed expiry, uint256 scaledTotalAmount, uint256 scaledAmountBurned, uint256 normalizedAmountPaid);

  event WithdrawalBatchPayment(uint256 indexed expiry, uint256 scaledAmountBurned, uint256 normalizedAmountPaid);

  event WithdrawalExecuted(uint256 indexed expiry, address indexed account, uint256 normalizedAmount);

  event WithdrawalQueued(uint256 indexed expiry, address indexed account, uint256 scaledAmount, uint256 normalizedAmount);

  event WrapperRegistered(address indexed wrapper);

  error AccountBlocked();

  error AmbiguousBorrowerIdentity();

  error AnnualInterestBipsTooHigh();

  error AprChangeOnClosedMarket();

  error AprReductionNotReduction();

  error BadLaunchCode();

  error BadRescueAsset();

  error BorrowAmountTooHigh();

  error BorrowFromClosedMarket();

  error BorrowWhileSanctioned();

  error BorrowerIdentityNotFound();

  error BorrowerPrincipalNotRegistered();

  error BorrowerTransferWhileSanctioned(address account);

  error CannotNukeWrapper();

  error CapacityChangeOnClosedMarket();

  error CloseMarketWithUnpaidWithdrawals();

  error DepositToClosedMarket();

  error ExecutePendingAprReductionNotEnabled();

  error FIFOQueueOutOfBounds();

  error InsufficientReservesForFeeWithdrawal();

  error InsufficientReservesForNewLiquidityRatio();

  error InsufficientReservesForOldLiquidityRatio();

  error InvalidArrayLength();

  error InvalidBorrower();

  error InvalidBorrowerIdentityRegistry();

  error InvalidBorrowerTransferTarget();

  error InvalidRepaymentTerms();

  error MarketAlreadyClosed();

  error MarketInRepayment();

  error MaxSupplyExceeded();

  error NoPendingBorrowerTransfer();

  error NoReentrantCalls();

  error NotApprovedBorrower();

  error NotApprovedLender();

  error NotFactory();

  error NotPendingBorrower();

  error NotWrapperFactory();

  error NullBurnAmount();

  error NullFeeAmount();

  error NullMintAmount();

  error NullRepayAmount();

  error NullTransferAmount();

  error NullWithdrawalAmount();

  error PendingBorrowerPrincipalChanged(address expectedPrincipal, address actualPrincipal);

  error ProtocolFeeChangeOnClosedMarket();

  error ProtocolFeeRecipientRequired();

  error ProtocolFeeTooHigh();

  error RepayToClosedMarket();

  error RepaymentReserveRequired();

  error ReserveRatioBipsTooHigh();

  error SphereXOperatorRequired();

  error UnsupportedExecuteWithdrawalHook();

  error WithdrawalBatchKeyAlreadyExists();

  error WithdrawalBatchNotExpired();

  error WrapperAlreadyRegistered();
}
