/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPeriodicTermHooks,
  IPeriodicTermHooksInterface,
} from "../IPeriodicTermHooks";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "providerAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "accountAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "credentialTimestamp",
        type: "uint32",
      },
    ],
    name: "AccountAccessGranted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "accountAddress",
        type: "address",
      },
    ],
    name: "AccountAccessRevoked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "accountAddress",
        type: "address",
      },
    ],
    name: "AccountBlockedFromDeposits",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "market",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "accountAddress",
        type: "address",
      },
    ],
    name: "AccountMadeFirstDeposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "accountAddress",
        type: "address",
      },
    ],
    name: "AccountUnblockedFromDeposits",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "market",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "annualInterestBips",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "proposalTimestamp",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "responseWindowStart",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "responseWindowEnd",
        type: "uint32",
      },
    ],
    name: "AnnualInterestBipsReductionProposed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "market",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "newMinimumDeposit",
        type: "uint128",
      },
    ],
    name: "MinimumDepositUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "name",
        type: "string",
      },
    ],
    name: "NameUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "market",
        type: "address",
      },
    ],
    name: "PeriodicTermClosed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "market",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "firstWithdrawalWindowStart",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "periodDuration",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "withdrawalWindowDuration",
        type: "uint32",
      },
    ],
    name: "PeriodicTermUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "providerAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "timeToLive",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint24",
        name: "pullProviderIndex",
        type: "uint24",
      },
      {
        indexed: false,
        internalType: "uint24",
        name: "pushProviderIndex",
        type: "uint24",
      },
    ],
    name: "RoleProviderAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "providerAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint24",
        name: "pullProviderIndex",
        type: "uint24",
      },
      {
        indexed: false,
        internalType: "uint24",
        name: "pushProviderIndex",
        type: "uint24",
      },
    ],
    name: "RoleProviderRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "providerAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "timeToLive",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint24",
        name: "pullProviderIndex",
        type: "uint24",
      },
      {
        indexed: false,
        internalType: "uint24",
        name: "pushProviderIndex",
        type: "uint24",
      },
    ],
    name: "RoleProviderUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "providerAddress",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "timeToLive",
        type: "uint32",
      },
    ],
    name: "addRoleProvider",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "blockFromDeposits",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "accounts",
        type: "address[]",
      },
    ],
    name: "blockFromDeposits",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "borrower",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "config",
    outputs: [
      {
        internalType: "HooksDeploymentConfig",
        name: "param0",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "marketAddress",
        type: "address",
      },
    ],
    name: "getHookedMarket",
    outputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "isHooked",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "transferRequiresAccess",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "depositRequiresAccess",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "withdrawalRequiresAccess",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "depositHookEnabled",
            type: "bool",
          },
          {
            internalType: "uint128",
            name: "minimumDeposit",
            type: "uint128",
          },
          {
            internalType: "uint32",
            name: "firstWithdrawalWindowStart",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "periodDuration",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "withdrawalWindowDuration",
            type: "uint32",
          },
          {
            internalType: "bool",
            name: "transfersDisabled",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isClosed",
            type: "bool",
          },
        ],
        internalType: "struct PeriodicTermHookedMarket",
        name: "param0",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "marketAddresses",
        type: "address[]",
      },
    ],
    name: "getHookedMarkets",
    outputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "isHooked",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "transferRequiresAccess",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "depositRequiresAccess",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "withdrawalRequiresAccess",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "depositHookEnabled",
            type: "bool",
          },
          {
            internalType: "uint128",
            name: "minimumDeposit",
            type: "uint128",
          },
          {
            internalType: "uint32",
            name: "firstWithdrawalWindowStart",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "periodDuration",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "withdrawalWindowDuration",
            type: "uint32",
          },
          {
            internalType: "bool",
            name: "transfersDisabled",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isClosed",
            type: "bool",
          },
        ],
        internalType: "struct PeriodicTermHookedMarket[]",
        name: "hookedMarkets",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "accountAddress",
        type: "address",
      },
    ],
    name: "getLenderStatus",
    outputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "isBlockedFromDeposits",
            type: "bool",
          },
          {
            internalType: "address",
            name: "lastProvider",
            type: "address",
          },
          {
            internalType: "bool",
            name: "canRefresh",
            type: "bool",
          },
          {
            internalType: "uint32",
            name: "lastApprovalTimestamp",
            type: "uint32",
          },
        ],
        internalType: "struct LenderStatus",
        name: "status",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getParameterConstraints",
    outputs: [
      {
        components: [
          {
            internalType: "uint32",
            name: "minimumDelinquencyGracePeriod",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "maximumDelinquencyGracePeriod",
            type: "uint32",
          },
          {
            internalType: "uint16",
            name: "minimumReserveRatioBips",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "maximumReserveRatioBips",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "minimumDelinquencyFeeBips",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "maximumDelinquencyFeeBips",
            type: "uint16",
          },
          {
            internalType: "uint32",
            name: "minimumWithdrawalBatchDuration",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "maximumWithdrawalBatchDuration",
            type: "uint32",
          },
          {
            internalType: "uint16",
            name: "minimumAnnualInterestBips",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "maximumAnnualInterestBips",
            type: "uint16",
          },
        ],
        internalType: "struct MarketParameterConstraints",
        name: "constraints",
        type: "tuple",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "marketAddress",
        type: "address",
      },
    ],
    name: "getPendingAprChange",
    outputs: [
      {
        components: [
          {
            internalType: "uint16",
            name: "annualInterestBips",
            type: "uint16",
          },
          {
            internalType: "uint32",
            name: "proposalTimestamp",
            type: "uint32",
          },
        ],
        internalType: "struct PendingAprChange",
        name: "pendingAprChange",
        type: "tuple",
      },
      {
        internalType: "uint32",
        name: "responseWindowStart",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "responseWindowEnd",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "accountAddress",
        type: "address",
      },
    ],
    name: "getPreviousLenderStatus",
    outputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "isBlockedFromDeposits",
            type: "bool",
          },
          {
            internalType: "address",
            name: "lastProvider",
            type: "address",
          },
          {
            internalType: "bool",
            name: "canRefresh",
            type: "bool",
          },
          {
            internalType: "uint32",
            name: "lastApprovalTimestamp",
            type: "uint32",
          },
        ],
        internalType: "struct LenderStatus",
        name: "status",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPullProviders",
    outputs: [
      {
        internalType: "RoleProvider[]",
        name: "param0",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPushProviders",
    outputs: [
      {
        internalType: "RoleProvider[]",
        name: "param0",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "providerAddress",
        type: "address",
      },
    ],
    name: "getRoleProvider",
    outputs: [
      {
        internalType: "RoleProvider",
        name: "param0",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "roleGrantedTimestamp",
        type: "uint32",
      },
    ],
    name: "grantRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "accounts",
        type: "address[]",
      },
      {
        internalType: "uint32[]",
        name: "roleGrantedTimestamps",
        type: "uint32[]",
      },
    ],
    name: "grantRoles",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "key0",
        type: "address",
      },
      {
        internalType: "address",
        name: "key1",
        type: "address",
      },
    ],
    name: "isKnownLenderOnMarket",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "marketAddress",
        type: "address",
      },
    ],
    name: "isWithdrawalWindowOpen",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "market",
        type: "address",
      },
    ],
    name: "pendingAprChanges",
    outputs: [
      {
        internalType: "uint16",
        name: "annualInterestBips",
        type: "uint16",
      },
      {
        internalType: "uint32",
        name: "proposalTimestamp",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "market",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "annualInterestBips",
        type: "uint16",
      },
    ],
    name: "proposeAnnualInterestBips",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "providerAddress",
        type: "address",
      },
    ],
    name: "removeRoleProvider",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "revokeRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "market",
        type: "address",
      },
      {
        internalType: "uint128",
        name: "newMinimumDeposit",
        type: "uint128",
      },
    ],
    name: "setMinimumDeposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_name",
        type: "string",
      },
    ],
    name: "setName",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "unblockFromDeposits",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "version",
    outputs: [
      {
        internalType: "string",
        name: "param0",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class IPeriodicTermHooks__factory {
  static readonly abi = _abi;
  static createInterface(): IPeriodicTermHooksInterface {
    return new utils.Interface(_abi) as IPeriodicTermHooksInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPeriodicTermHooks {
    return new Contract(address, _abi, signerOrProvider) as IPeriodicTermHooks;
  }
}
